superfly/docs

- reference/metrics.html.md
This removes the section utilizing `metrics_*` keys under the `experimental` table, based on the assumption they are no longer relevant now that there is a dedicated `metrics` table.
> remove duplicated/outdated experimental metrics docs

- hands-on/connecting-to-an-app.html.md
I was going through the hands-on demo and noticed that `flyctl open /to/fred` actually opened my browser to a 404 page instead of what's shown in the screen shot.  The issue seems to be that the demo container doesn't actually support the `/to/:token` route, only `/:token` seems to work.  
Note that in addition my change below the screen shot also needs to be updated as well (I have a bunch of pinned tabs in my Safari so can't reproduce the image without closing them all), it seems like the app deployed at `hellofly` also expects just `/:token`.
> minor: discrepancy in hellofly demo

- getting-started/deno.html.md.erb
- getting-started/elixir.html.md.erb
- getting-started/golang.html.md.erb
- getting-started/node.html.md.erb
- getting-started/partials/_intro.html.md.erb
- getting-started/python.html.md.erb
- getting-started/ruby.html.md.erb
- getting-started/static.html.md.erb
This PR unifies the slightly different language across the Getting Started guides. The partial logic may be overengineered but works as a starting point.
> Move the getting started guide intros into a shared partial

- .gitignore
- app-guides/custom-domains-with-fly.html.md
- app-guides/nats-cluster.html.erb
- app-guides/run-a-global-image-service.html.md.erb
- app-guides/smokescreen.html.erb
- app-guides/speed-up-a-heroku-app.html.md.erb
- guides.html.erb
- partials/_firecracker_nav.html.slim
These guides stay in place for SEO reasons. Links from the sidebar and the main guides page go away. The goal now is to reintroduce important content in official guides that we intend to keep up-to-date with flyctl.
> Remove links to stale guides

- reference/configuration.html.md
References this community post: https://community.fly.io/t/change-a-containers-cmd-via-the-fly-toml-file/2536
> Add `cmd` section to experimental

- reference/postgres.html.md
Changed "sentinal" to "sentinel".
Based on the spelling in the official [README](https://github.com/sorintlab/stolon/blob/master/README.md#architecture).
> Fix typo in Postgres reference docs

- signup-welcome.html.md
Also mentioned here: https://community.fly.io/t/http-404-forbidden-error-from-signup-welcome-page/2881
> Hands-on link wrong

- getting-started/ruby.html.md.erb
The Ruby guide contained an example `fly.toml` in which the `build.buildpacks` key contained a string which was missing the closing `¨`.
This change adds this quotation mark.
> Fixes typo in Ruby guide

- about/pricing.html.md.erb
All other 2x2 VM+Volume configurations have accurate pricing, however the 2x $10.70 + 2x $6 was listed as a total of $27.40. Original author only calculated 2x $10.70 and 1x $6.
> Update Postgres Clusters total pricing accuracy

- flyctl/cmd/flyctl_wireguard_create.md
- reference/private-networking.html.md
Based on conversation at https://community.fly.io/t/unable-to-dig-peer-internal-when-default-name-is-used/4037/2
> Notes on peers

- getting-started/partials/_launch.html.md.erb
- getting-started/partials/_launched.html.md.erb
- getting-started/rails.html.md.erb
- getting-started/remix.html.md.erb
- partials/_firecracker_nav.html.erb
Closes https://github.com/fly-apps/rails-nix/issues/19
Adds a basic documentation page for launching Rails apps. 
Not covered yet (up next):
- Multiprocess apps, launching with Sidekiq and Redis.
- More detail on the `fly.toml` file
- Deployment options; Buildpacks, Docker.
> Add initial Rails guide

- reference/volumes.html.md
Noticed while using `flyctl` the flag for creating an unencrypted volume was incorrect in the documentation. This PR corrects it.
> Corrects the flag for skipping volume encryption

- getting-started/crystal.html.md.erb
I don’t know what flavor of markdown the main site is working, but the code blocks inside of the ol ’s will likely need to be redone if this isn’t github flavored markdown
> Add multi-region docs to Run a Crystal App guide

- app-guides/run-a-global-image-service.html.md.erb
- app-guides/run-a-private-dns-over-https-service.html.md.erb
- app-guides/udp-and-tcp.html.md.erb
- flyctlhelp.html.md
- getting-started/crystal.html.md.erb
- getting-started/deno.html.md.erb
- getting-started/golang.html.md.erb
- getting-started/log-in-to-fly.html.md
- getting-started/node.html.md.erb
- getting-started/python.html.md.erb
- getting-started/rails.html.md.erb
- getting-started/ruby.html.md.erb
- getting-started/static.html.md.erb
- hands-on/sign-in.html.md
- hands-on/sign-up.html.md
- partials/_firecracker_nav.html.erb
👋 Hey folks! I noticed that the docs had multiple places where it referenced `Github` instead of `GitHub`, which is the correct capitalization. I went through and corrected these.
VS Code also removed some trailing whitespace on some lines too it seems, sorry about that noise in the diff.
It looks like your website also has some places with the lowercase `h`, if you don't mind passing that along to the folks who can fix that as well 😅:
> Use correct capitalization of GitHub

- app-guides/multiple-processes.html.md
overmind captures SIGTERM and cleans itself up by deleting `.overmind.sock`, but in order for this to work correctly it needs to run in Exec form, which is the recommended by docker (https://docs.docker.com/engine/reference/builder/#cmd)
> Update overmind CMD to use Exec form

- reference/redis.html.md
"such a caching" -> "such as caching"
> Fix a small typo in the Redis reference

- reference/metrics.html.md
This PR should also demystify the units on ambiguous values like those named `*disk_time*`
> Add all available Fly-exposed metrics to metrics docs

- getting-started/edgedb.html.md
- partials/_firecracker_nav.html.erb
Per a Twitter DM with a Jerome, this is an EdgeDB deployment guide. We're recommending Fly to most folks using EdgeDB in production since the deployment experience is a lot cleaner than with the big clouds. EdgeDB itself is a a stateless container that runs on top of Postgres, so it slots neatly into Fly's abstraction.
This document is a leaner, meaner version of our original Fly deployment guide on our site: https://www.edgedb.com/docs/guides/deployment/fly_io I added it to the `getting-started` subdirectory and added it to the sidebar under the "Redis on Fly" guide, though happy to move it wherever you think is appropriate!
> Add EdgeDB deployment guide

- getting-started/edgedb.html.md
Small mistake - future commands expect a `fly.toml` (no `--app`) is specified for all commands relating to the EdgeDB app.
> Use launch instead of apps create

- reference/configuration.html.md
It appears that the example in the docs using the Paketo tiny builder results in an error, as the node buildpack lists itself as incompatible with the tiny stack.
To that end, adjusted the docs to use the base builder instead, which throws no such error.
> Adjust the paketo example to use the base builder

- reference/monorepo.html.md
Seems like the flag should be lowercase as shown earlier on the page
> fix dockerfile flag on monorepo page

- getting-started/laravel.html.md.erb
This PR is dependent on https://github.com/superfly/flyctl/pull/1058/files, which allows us to remove the prompt for generating a needed secret for Laravel apps.
> Updating docs for the Laravel launcher

- reference/configuration.html.md
Call out known issues with the `processes` directive when scheduling images across multiple regions.
> Call out known issues with the processs scheduler across regions

- rails/the-basics/run-tasks-and-consoles.html.md
I spent a few minutes trying to connect with -c when I really needed -C instead for the Rails console.
--
I'm unsure if this is worthy of an issue / doc fix... but I also had to prefix my commands with the WORKDIR from my Dockerfile that was generated by `fly launch` (app/) to make the commands work... so `bin/rails console` (doesn't work) -> `app/bin/rails console` (works)
> Update flag for rails console command

- rails/the-basics/run-tasks-and-consoles.html.md
`bin/rails` is the preferred way to run the `db:migrate` subcommand (and all other Rails subcommands).  Therefore, it would be better to suggest an arbitrary task for the `bin/rake` example.
> Avoid using `rake` for `rails` subcommand

- rails/the-basics/sidekiq.html.md
On https://fly.io/docs/rails/the-basics/sidekiq/, the "outlined in the multiple-proccesses" link returns a Nginx 404 page when you click it. It needs to be https://fly.io/docs/app-guides/multiple-processes not https://fly.io/docs/app-guides/multiple-processes.html.md.
> Fix 404ing link

- rails/the-basics/configuration.html.md
For Rails, there is a `config/credentials.yml.enc` file, and there are also environment-specific credentials files such as `config/credentials/production.yml.enc`, but no `credentials.yml` file.
> Remove references to `credentials.yml`

- rails/the-basics/configuration.html.md
Credentials often include sensitive data, so it would be better to not suggest putting them in `fly.toml`.
This commit also changes the `fly.toml` example variable from `LOCALE` to `RAILS_LOG_TO_STDOUT`, to avoid implying that `LOCALE` has any effect by default, such as setting `I18n.default_locale`.  (Note that `RAILS_LOG_TO_STDOUT` only [has to be a nonblank string][1], so the example value used here is `x`, to avoid a boolean connotation.)
[1]: https://github.com/rails/rails/blob/v7.0.3/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt#L97
> Consider credentials as sensitive data

- app-guides/planetscale.html.md
- getting-started/edgedb.html.md
- getting-started/multi-region-databases.html.md
- reference/metrics.html.md
- reference/monorepo.html.md
- Guides and Examples / Use a PlanetScale Database
- Quickstart Guides / Multi-region PostgreSQL
- Quickstart Guides / Run EdgeDB on Fly
- Fly Reference / Metrics
- Fly Reference / Monorepo Apps
> Add language attribute to single-line shell blocks

- reference/postgres.html.md
There was a small typo in the user role docs where is started `us` rather than `use` ... see commit for context!
> Small typo in postgres user role docs

- rails/the-basics/sidekiq.html.md
Since Puma v2.8.0 (puma/puma@7d7a1fbebe4dde2edf045ada80730ce4f41c4cd5), Puma will automatically use `config/puma.rb` if it is present, so specifying `-C config/puma.rb` is not necessary.  (See the [Configuration File section][1] of the Puma README for more information.)
[1]: https://github.com/puma/puma/blob/v5.6.4/README.md#configuration-file
> Remove Puma `-C config/puma.rb` option

- flyctl/cmd/flyctl_postgres_detach.md
- getting-started/edgedb.html.md
- getting-started/legacy_elixir.html.md.erb
- getting-started/multi-region-databases.html.md
- rails/the-basics/backup-and-restoring-data.html.md
- reference/postgres.html.md
There is a reference to a `--postgres-app` flag in several examples and guides, however based on version `v0.0.377` this flag no longer exists. This flag was also removed from the docs recently in pr https://github.com/superfly/docs/pull/237 .
This pr just removes the `--postgres-app` flag from each example. And, for reference here is a session screenshot from attempting to use this flag with `fly attach` and `fly detach`.
> Remove `--postgres-app` Flag From Documentation Related to `fly attach`

- reference/metrics.html.md
- d61ff1ade62b694746006e04d8c5dd9d62435b5f - fix `fly_instance_cpu` time unit. CPU time is measured in clock ticks of centiseconds (0.01 seconds), not seconds.
- b86797dfedf2eee0643bae65cf21fc76c41290a0 - Add information about [MetricsQL](https://docs.victoriametrics.com/MetricsQL.html), which is the query language used for queries to the managed Prometheus service. It's mostly backwards compatible with PromQL, but has some key differences including a few extra features and conveniences worth noting.
> Updates to metrics docs

- getting-started/multi-region-databases.html.md
This is super minor but annoying: atl region does not exist, and trying to create a replica in the region throws an error.
> Remove references to atl region

- app-guides/custom-domains-with-fly.html.md
There is a Cloudflare setting that interferes with SSL cert validation. Advise to disable this feature.
https://community.fly.io/t/ssl-cert-wont-issue-cloudflare-phantom-txt-record/6575
> Custom Domains - SSL - Add Troubleshooting section

- rails/the-basics/deployments.html.md
Fix spelling of `ssets:precompile` to `assets:precompile`
> Fix spelling of `ssets:precompile`

- flyctl/installing.html.md
- hands-on/partials/_launch-app.html.md
- hands-on/partials/_next.html.md
- described all CLI prompts from the fly launch command
- mentioned that the flyctl directory should be added to the rc file
- add a link to getting started with laravel on fly.io
> Small changes to the getting-started docs

- reference/machines.html.md.erb
Found one typo so I did a quick sweep and found a few more others. 
Fon -> For
enviornment -> environment
accesible -> accessible
> fix: typos in machines.html.md.erb

- languages-and-frameworks/dockerfile.html.md.erb
I was following [Deploy via Dockerfile](https://fly.io/docs/languages-and-frameworks/dockerfile/) guide an encountered errors when defining my environment variables in `fly.toml`. After consulting the [fly.toml env vars docs](https://fly.io/docs/reference/configuration/#the-env-variables-section) and following that format everything worked fine.
This PR updates the `fly.toml` code snippet to the correct format.
> Update [env] code snippet to match correct format

- laravel/index.html.md.erb
- laravel/the-basics/cron-and-queues.html.md
- laravel/the-basics/customizing-deployments.html.md
- laravel/the-basics/databases.html.md
- laravel/the-basics/logging-stack-traces.html.md
- laravel/the-basics/post-deployment.html.md
- reference/configuration.html.md
1. Added a mention in the `release_commands` docs about new env var `RELEASE_COMMAND=1` that is set in the temporary VM created to run release commands
2. Added a new section to the Laravel Docs "Customizing Deployments" to mention a new feature in the Laravel launcher - user-scripts, that are run whenever an app VM is started (via `ENTRYPOINT`).
- this section will be useful for future customization notes as well
> Laravel docs: Customize Deploys

- reference/private-networking.html.md
If the wireguard config name is longer than 15 chars, `wg-quick` will comlain that the name doesn't exist.
> Mention max iface name length

- rails/getting-started/index.html.md
The last sentence on this page says `it is time to move on to [The Basics](https://fly.io/docs/the-basics/).` but that link 404's.
However on the rendered page just below it there's a list of "Additional Resources" which includes a link to `[The Basics](https://fly.io/docs/rails/the-basics/)` which works -- so this PR makes the broken link match the working link.
> Fix broken link to "The Basics"

- reference/postgres-whats-next.html.md
The links to Postgres doc were pointing to an inexistent file.
> Fix links to postgres doc

- getting-started/log-in-to-fly.html.md
I really just came to fix **'a details'**, but then noticed a couple of other things.
'sign in' for verb form, 'sign-in' for adjective form; 2 clauses separate with semicolon
> grammar correction to log-in-to-fly.html.md

- reference/scaling.html.md
The autoscaling documentation hasn't been updated since we changed the autoscaling implementation to nomad-based autoscaler in Sept 2021. Notably, the Scale Mode configuration no longer has any effect. This PR updates the `Autoscaling` section to more accurately reflect the current system's behavior.
This documentation update matches changes in superfly/flyctl#1429.
> Update autoscaling docs

- reference/scaling.html.md
the command `fly platform vm-sizes` does not show the current pricing for each vm
> `fly platform vm-sizes` does not show pricing

- app-guides/continuous-deployment-with-github-actions.html.md
Changes:
* Use `on: push: branches: - main` instead of `on: [push]` since this will cause deploys even on pushes to Pull Requests which do not affect the main build. By specifying the branch, it will only deploy when the main branch is updated (via push or merged Pull Request).
* Name the workflow `fly.yml` which describes what it is for instead of `main.yml`.
* Use `actions/checkout@v3` which is the latest version instead of `actions/checkout@v2`
> Improvements to the GitHub action example

- getting-started/working-with-fly-apps.html.md
`cmd` has an extra prompt, when it's copied it's invalid due to `>`.
> Remove prompt in Working with Fly Applications

- app-guides/6pndemochat.html.erb
- app-guides/git-gogs-server.html.erb
- app-guides/global-nginx-proxy.html.md
- app-guides/graphql-edge-caching-apollo.html.erb
- app-guides/graphql-on-fly-with-hasura.html.md
- app-guides/grpc-and-grpc-web-services.html.erb
- app-guides/kong-api-gateway.html.erb
- app-guides/mqtt.html.erb
- app-guides/nginx-at-the-edge.html.md.erb
- app-guides/node-red.html.erb
- app-guides/openresty-nginx-plus-lua.html.erb
- app-guides/postgres.html.erb
- app-guides/puppeteer-js-renderer.html.erb
- app-guides/redis.html.erb
- app-guides/redistls.html.erb
- app-guides/run-a-global-image-service.html.md.erb
- app-guides/smokescreen.html.erb
- app-guides/speed-up-a-heroku-app.html.md.erb
- app-guides/vscode-remote.html.erb
- partials/_obsolete_doc.html.erb
Many old (2020-era) guides are still reachable, even though we took them out of the menus. Some are linked from blog posts, others from fly-apps repos. 
Added an obsolete warning to as many as I found, using a partial, as a nondestructive step.
> add obsolete message for old guides

- postgres/getting-started/migrate-from-heroku.html.md
On the very last line of this file there is a link leading to "/docs/postgres/this-basics/connecting". This link is broken. I believe the link should actually be to "/docs/postgres/the-basics/connecting". Changing the word "this" to "the" within the link.
> Update broken link on migrate-from-heroku.html.md

- elixir/advanced-guides/github-actions-elixir-ci-cd.html.md
- laravel/the-basics/github-actions.html.md
- rails/getting-started/migrate-from-heroku.html.md
`GitHub` is spelled with a capital H.
Disclosure: I am a GitHub employee.
> fix capitalization of GitHub

- postgres/getting-started/migrate-from-heroku.html.md
Without the backticks around the variable name the "_DATABASE_" text is converted to italics.
> Quote environment variable in Markdown

- hiring/roles.html.md
> Typo fix in "Engineering Roles" page

- postgres/managing/users-and-roles.html.md.erb
The rest of the Postgres docs includes the `-a` app flag as opposed to referring to a local fly.toml file, so I'd imagine the like the lack of it here is a typo.
Flyctl returns this error message as expected when the command is run without the `-a` flag or a local Postgres app project, `Error we couldn't find a fly.toml nor an app specified by the -a flag. If you want to launch a new app, use 'flyctl launch'`
> Add missing "-a" app flag to command

- litefs/config.html.md.erb
- litefs/files.html.md.erb
- litefs/getting-started.html.md.erb
- litefs/how-it-works.html.md.erb
- litefs/index.html.md.erb
- litefs/partials/_disclaimer.html.md
We have a "beta" tag on the GitHub repo but I forgot to add a callout to the docs. There are definitely some rough edges with LiteFS still so I want to be clear about its level of stability.
> Add beta disclaimer to LiteFS docs

- about/pricing.html.md.erb
- machines/guides-examples.html.md
- machines/guides-examples/machine-sizing.html.md.erb
- machines/working-with-machines.html.md.erb
Using https://github.com/superfly/landing/pull/362 to display pricing on the official pricing page
1. Updated pricing page
2. Added to guides/examples with examples on setting/updating Machine VM sizes
> Machines pricing

- app-guides/mysql-on-fly.html.md
This is closely related to the manual at the [PostgreSQL side](https://fly.io/docs/reference/postgres-on-nomad/#connecting-to-postgres-from-outside-fly), but I still felt like adding this here for better observability.
Hope that helps!
> Add chapter about accessing MySQL using `fly proxy`

- machines/guides-examples/functions-with-machines.html.md.erb
h/t: [danthegoodman](https://community.fly.io/t/9168).
> guide(faas): tired-proxy timeout is 120s not 4s

- litefs/example.html.md.erb
- litefs/index.html.md.erb
The _Getting Started_ guide was renamed to be an "example application". I'm going to add an actual _Getting Started_ guide at some point so this is a stop gap.
> Add LiteFS getting started redirect

- reference/redis.html.md
Noticed in passing... was linking to non-existant getting-started/install...
> Fixed link to install flyctl

- laravel/advanced-guides/global-sqlite-litefs.html.md.erb
- laravel/the-basics/databases.html.md.erb
- laravel/the-basics/github-actions.html.md
Adding "Laravel" into the title of doc sections helps identify section is Laravel specific. This helps in providing descriptive search results
> Add Laravel to general laravel docs like database,litefs,cicd

- postgres/getting-started/create-pg-cluster.html.md.erb
While browsing the docs for setting up a AppsV2 postgres i stumbled across a link to the global replication guide, which did not work. I think this was meant to link to the advanced guides section?
> fix: link to high-availability-and-global-replication

- machines/working-with-machines.html.md.erb
Stumbled across this on:
https://fly.io/docs/machines/working-with-machines/
> correct anchor link on machines/working-with-machines to wait-for-a-machine-to-reach-a-specified-state

- hands-on/install-flyctl.html.md.erb
The docs clearly indicate that the installation script needs powershell, but I run in git-bash and always have to spin up a separate shell for the installation script. This ensures that the command always works regardless of the user's current shell.
I've tested the command itself, but because I don't have access to the landing repo, I haven't ensured that the Copy button captures the command correctly and works. Happy to either do that myself or hand it off to someone else.
> Always run Windows flyctl installation command in powershell.

- postgres/getting-started/migrate-from-heroku.html.md
The migration process can now be simplified by leveraging `fly pg import`.
> Migrating from heroku can now use import tool

- reference/load-balancing.html.md
Avoids markdown formatting italicizing text, and makes it consistent with the rest of the page
> Put soft_limit and hard_limit in code blocks

- getting-started/troubleshooting.html.md
I'm a big fan of Fly.io and recently deployed a Node.js app running Fastify on the platform. The latest release of Fastify (version 4) changed the signature of the listen function to `.listen([options][, callback])`. This PR updates the troubleshooting guide so the Fastify hello world example matches what's on the [Fastify home page](https://www.fastify.io/).
Fastify docs for listen(): https://github.com/fastify/fastify/blob/main/docs/Reference/Server.md#listen
> update fastify example to work with latest release

- reference/services.html.md.erb
The proxy timeout confuses people in [various](https://twitter.com/aweary/status/1633926337890078720) ways. So, here's a first shot at documenting it for public proxy services.
> Add documentation about the 60-second proxy timeout

- reference/volumes.html.md.erb
Fixing text referring to the example on the docs.
As pointed out here: https://community.fly.io/t/documentation-heavily-outdated-for-volumes/12288/3
> Fixing example volume creation region

- getting-started/troubleshooting.html.md
on Troubleshooting you Deployment section
> Adding a note about non-http(s) ports and shared/dedicated ip addresses

- hands-on/install-flyctl.html.md.erb
- hands-on/launch-app.html.md.erb
This PR:
- Edits to Launch page:
- Updates the `fly launch` prompts in Hands on with Fly.io > Launch an App on Fly
- Made some edits to language, added a link, and some other minor nitpicks, which you're welcome to disagree with!
- Edits to Install page:
- For macOS, the info about adding the path to the .zshrc file only applies to curl install, so clarified that
- The next steps at the bottom were not clearly separate from the last section like they are for other pages, so tried to make that clearer.
Docs affected:  
- https://fly.io/docs/hands-on/launch-app/
- https://fly.io/docs/hands-on/install-flyctl/
---  
Note: I tested this change locally on middleman and noticed that the content is centered rather than left aligned? Not sure If I did something or if that's normal?
| Production | …
> Update launch prompts in Hands-on section

- apps/autostart-stop.html.md.erb
- apps/index.html.md.erb
- partials/_firecracker_nav.html.erb
- reference/configuration.html.md.erb
This PR: 
- adds a new page under Apps about automatically stopping and starting Machines
- adds the new settings to the fly.toml config doc page
- adds new page to sidenav and apps index page
Source material: https://community.fly.io/t/automatically-starting-stopping-apps-v2-instances/12342
Tested locally. See comments for questions/issues.
> Add autostart and stop docs

- partials/_firecracker_nav.html.erb
add missing `=` in new nav link tag
> Fix nav link tag

- reference/configuration.html.md.erb
@brenol pointed out some clarifications for the release command option in fly.toml. (https://github.com/superfly/docs/pull/690) 
Github's not letting me make suggestions on the PR and I wanted to change some more things, thus this new PR
> config doc: clarify how release_command works

- elixir/advanced-guides/connect-livebook-to-your-app.html.md
One more broken link. When GitHub parses this, it determines that it's not a link at all, but on the documentation site it links to `https://fly.io/docs/elixir/advanced-guides/connect-livebook-to-your-app/(https://livebook.dev/#install)`.
> fix broken livebook desktop link

- apps/autostart-stop.html.md.erb
- apps/scale-count.html.md.erb
In preparation for new app scaling doc based on new `fly scale count` functionality
> move exit-from-within discussion to autostart doc

- partials/_v2_transition_banner.html.erb
- reference/apps.html.md.erb
This was way too long, and not so much info is needed now that V2 has been around for a while.
Also distinguish banner from the new callout style. It ain't exactly pretty.
> shorten v2 banner; move some of it to apps ref doc

- app-guides/mysql-on-fly.html.md
- app-guides/mysql-on-fly.html.md.erb
- laravel/the-basics/databases.html.md.erb
This PR: 
- was prompted by this community post: https://community.fly.io/t/noobies-question-mysql-vol-not-being-populated/12481
- updates the [Use a MySQL Database](https://fly.io/docs/app-guides/mysql-on-fly/) page:
- moves the fly.toml into a new section for Apps V1 and adds a new parallel section for Apps V2
- changes the number of daily snapshots we keep from 7 to 5
- updates the Laravel and Databases page:
- added a parallel step for adding redis password commands for V2
> Some apps v2 updates for MySQL and Laravel DB docs

- postgres/index.html.md
Fixes the spelling error on [this page](https://fly.io/docs/postgres/) of the docs. Changes `aslo` to `also`.
> Fix spelling error

- machines/guides-examples/terraform-machines.html.md.erb
The old link redirects into an AWS workflow in the Terraform docs. New link goes to generic downloads page.
> Update terraform download link

- rails/getting-started/migrate-from-heroku.html.md
`grep` is **excluding** those commands, not keeping them, as the doc is saying.
> Fix "Migrate from Heroku" guide on secrets importing

- apps/volume-storage.html.md.erb
- database-storage-guides.html.md
- partials/_firecracker_nav.html.erb
- reference/volumes.html.md.erb
**Work in Progress**
- The goal of the structure changes is to move content around so that the "Databases & Storage" page is an overview of all storage options, "Volumes reference" is where you find all the details, and "Add Volume Storage" comes after you've chosen storage and read the Volume reference (hopefully).
- Consolidate and make descriptions consistent
- These community posts gave us some direction on what was needed: https://community.fly.io/t/documentation-heavily-outdated-for-volumes/12288 and https://community.fly.io/t/some-issues-with-volumes-on-apps-v2/11994
Preview: https://andrea-docs-preview.fly.dev/docs/database-storage-guides/
- moved section on `choosing your approach to storage` here
- minor edits
Preview: https://andrea-docs-preview.fly.dev/docs/reference/volumes/ …
> Update volume docs for clarity and user feedback

- reference/machines/wait_req.html.md
It's not super obvious how to pass in state as a query param to the wait endpoint, and especially since [this was reported in the forum](https://community.fly.io/t/machines-api-for-waiting-a-machine-for-state-is-not-clear/12516), thought it'd be an easy fix
> Add query params to wait endpoint example to make request clearer

- apps/volume-storage.html.md.erb
- reference/volumes.html.md.erb
Add 2 ways to add volumes to existing apps (apps that have already been deployed). 
- clone and use --attach-volume, specifying the mount point
- set up volumes and run `fly deploy`
Other minor edits. Like renaming Add and Use Volume Storage back to just Add Volume Storage. We need to add more info about usage or maybe link to the specific framework guides that talk about volumes?
> Update volume docs with more ways to add volumes

- machines/working-with-machines.html.md.erb
While reading the machines docs, I found a broken link! Fixed here.
> Fix link to setting up machines section in working with machines

- machines/guides-examples/terraform-machines.html.md.erb
- machines/working-with-machines.html.md.erb
- reference/machines/create_app.html.md
- reference/machines/create_app_req.html.md
- reference/machines/delete.html.md
- reference/machines/delete_app.html.md
- reference/machines/delete_app_req.html.md
- reference/machines/delete_req.html.md
- reference/machines/get.html.md
- reference/machines/get_app.html.md
- reference/machines/get_app_req.html.md
- reference/machines/get_req.html.md
- reference/machines/launch.html.md
- reference/machines/launch_req.html.md
- reference/machines/launch_syd_req.html.md
- reference/machines/lease.html.md
- reference/machines/lease_req.html.md
- reference/machines/list.html.md
- reference/machines/list_req.html.md
- reference/machines/start.html.md
- reference/machines/start_req.html.md
- reference/machines/stop.html.md
- reference/machines/stop_req.html.md
- reference/machines/update.html.md
- reference/machines/update_req.html.md
- reference/machines/wait.html.md
- reference/machines/wait_req.html.md
I made some improvements while working from the working with machines docs:
* Most importantly: don't send fly API token in header over http when using `api.machines.dev` (instead use https)
* Make the Terraform examples 1% easier to copy-and-paste by using `fly_app`'s `name` attribute instead of making the user update the name in multiple places
* Added a line explaining where to get the auth token when setting up env for machines API
> Working with machines improvements

- machines/guides-examples/machines-app-using-flyctl.html.md.erb
link to `fly machine` command docs had a typo
> Fix link typo

- apps/volume-storage.html.md.erb
- reference/volumes.html.md.erb
An attempt to organize and augment the information about volumes by adding details, using headings, and summarizing and adding to the considerations. Will need a technical review. 
- Moved content out from the Create a volume section into the overview and into separate sections about regions and high availability.
- Added bolded "summary" statements to the bullets in the Considerations section to make them easier to scan visually.
- Created parallel considerations to explain the one-to-one mapping between volumes, regions, apps, and Machines.
- Etc.
> Volume reference re-org

- apps/autostart-stop.html.md.erb
- reference/configuration.html.md.erb
This PR:
- adds the `min_machines_running` setting to the auto start and stop docs (source: https://community.fly.io/t/setting-a-minimum-number-of-instances-to-keep-running-when-using-auto-start-stop/12861)
- adds a note to emphasize this feature is for existing Machines only
- includes some other clarifications and word improvements
- updates the fly config reference for fly.toml
> Add min machines running to auto start/stop feature docs

- app-guides/continuous-deployment-with-github-actions.html.md
This PR:
- fixes the issue where the token is created before the app, which doesn't work, by rearranging the steps
- removes the step about .gitignore but adds a note
- updates the steps for adding a repo secret in gh
- other edits
> Update order of steps + other stuff for Continuous Deployment doc

- elixir/getting-started/existing.html.md.erb
- elixir/the-basics/iex-into-running-app.html.md
- rails/the-basics/deployments.html.md
- rails/the-basics/run-tasks-and-consoles.html.md
It looks like we're going to change the SSH working directory to the Docker image's `WORKDIR` by default, so the docs shouldn't assume that it will be `/`.
Provided that our scanner-generated `Dockerfile`s set the `WORKDIR` properly, we may want to further update some of these commands when that patch rolls out (e.g. simplifying `/rails/bin/rails` to `bin/rails`). But for now I just want to make sure that they keep working!
> Use absolute paths for SSH commands

- litefs/backup.html.md.erb
- litefs/config.html.md.erb
- litefs/export.html.md.erb
- litefs/getting-started.html.md.erb
- litefs/how-it-works.html.md.erb
- litefs/import.html.md.erb
- litefs/index.html.md.erb
- litefs/migrations.html.md.erb
- litefs/mount.html.md.erb
- litefs/partials/_disclaimer.html.md
- litefs/position.html.md.erb
- litefs/primary.html.md.erb
- litefs/proxy.html.md.erb
- litefs/run.html.md.erb
- partials/_litefs_nav.html.erb
Previously, there was a banner on every page noting that LiteFS was beta and not ready for production. That is probably overly cautious advice at this point. LiteFS is stable and is in production deployments.
Instead, a "project status" section has been added to the home page of the LiteFS docs to note its pre-1.0 status and also recommend that people use a cluster backup strategy. That's good advice for any database, honestly.
/cc @kentcdodds
> Remove LiteFS banner; replace with project status disclaimer

- apps/volume-storage.html.md.erb
A kind of important part of the command was missing to create a volume. 😊
> Fix missing command

- reference/configuration.html.md.erb
This PR:
- sprinkles more "processes" stuff throughout, where it was missing
- adds the `console_command` field
- fixes up `min_machines_running`
- adds the `ignorefile` field to the build section
- adds `http_options.response.headers` to `http_service` and `services`
- other minor edits
Preview: https://aa-docs.fly.dev/docs/reference/configuration/
> Updates to Application Configuration docs

- rails/getting-started/dockerfiles.html.md
The "M" in RAM already stands for memory. 
Love Fly, and love your extensive docs. Thanks for all the work you put in on them!
> Remove redundant wording

- speedrun.html.md.erb
some changes to consider
- add the location to run `fly launch` in there
- fix the links to the heroku launcher
- enhance the list of "want to learn more?" Link to storage, apps, and comprehensive framework guides
**PREVIEW: https://aa-docs.fly.dev/docs/speedrun/**
> Possible speedrun updates

- django/index.html.md.erb
Add [Django Beats Blog](https://fly.io/django-beats/) to Django Docs.
> Add blog to Django docs

- reference/configuration.html.md.erb
Canary is now available in v2, so only bluegreen should be listed as an exception for Nomad.
> Remove duplicate references to the canary strategy

- going-to-production/monitoring/exporting-logs.html.md
Incorrect link for NATS.
Was `nats.io` which results in a relative (i.e. `https://fly.io/docs/going-to-production/monitoring/exporting-logs/nats.io`) reference rather than `https://nats.io`
> Incorrect link r|nats.io|https://nats.io

- postgres/managing/scaling.html.md.erb
Just found this small typo while reading the docs!
> Fix typo in Postgres scaling docs

- apps/autostart-stop.html.md.erb
Add the info that auto start and stop respects the configured `kill_signal` and `timeout_signal` settings. 
source: https://community.fly.io/t/autostop-now-respects-kill-signal-and-timeout/13502
Plus other minor fixes.
> Update to add kill_signal support and minor edits

- django/getting-started/index.html.md
Update Django "Getting Started" page:
- Use https://github.com/fly-apps/hello-django as the example so users can follow along.
- Add some additional info like creating and activating the virtual environment.
- Remove parts that are not relevant anymore after some changes on `flyctl` (e.g. `collectstatic` command on Dockerfile)
- Add some links to the [repository](https://github.com/fly-apps/hello-django) direct into the docs to make it easier to see the example source code.
> [django] Update Django Docs: Getting started

- machines/working-with-machines.html.md.erb
Users occasionally post about trouble with the Machines API where they've included the example app name in their commands. I added a warning-style callout and some prose in some sections reminding the user that `user-functions` is the example name.
We could still dig in and replace `user-functions` with `example-machines-app-name` or something, but I'm leaving that for now, because the content's coming from a bunch of partials and I don't know whether that affects the user code guide.
Also converted some titles to sentence case. We had a mixture in this file.
> Machines API: clarify user-functions is an example app name

- postgres/managing/scaling.html.md.erb
This PR styles the note about Postgres VM RAM and tuning config parameters into a warning. Also some minor re-wording.
> Postgres docs: change text about VM RAM to a warning

- reference/configuration.html.md.erb
My toml linter complains about this and also received a validation error from flyctl
> [Formatting] fix trailing comma in `tls_options`

- apps/deploy.html.md.erb
- reference/configuration.html.md.erb
This PR updates the docs to remove the limitation of no bluegreen deploy strategy for V2 apps.
Source: https://github.com/superfly/flyctl/pull/2458
> Update docs for bluegreen deploy strategy in V2 apps

- hiring/company-levels.html.md
- hiring/working.html.md
- partials/_devjobs_nav.html.erb
The https://fly.io/docs/hiring/levels/ page has Engineering-specific language in it, and we hire for more than just engineering roles!
I've added a company levels page (using the same basic language as the Engineering page, just a little more genericized) which we can link to as necessary for outside-of-Engineering roles.
I've also added the word "Engineering" to the sidebar nav link for levels, and a link to those engineering levels from the main hiring page (in case folks want to read more depth).
> Clarifying engineering levels vs. company-wide levels

- apps/processes.html.md.erb
This PR changes a sentence about the default `app` process group in the default `fly.toml` file. 
Source: https://github.com/superfly/flyctl/pull/2446
> Update process group doc for toml change

- apps/index.html.md.erb
- getting-started/index.html.md
- hands-on/index.html.md.erb
- hands-on/launch-app.html.md.erb
- hands-on/next.html.md.erb
- hands-on/open-app.html.md.erb
- index.html.md
- partials/_firecracker_nav.html.erb
- partials/_hands_on_nav.html.erb
- speedrun.html.md.erb
This PR:
Updates mainly two of the Gettting started sections to use Fly Launch, plus some other minor edits:
- Speedrun
- Hands-on
Updates the main Docs index page.
- some changes are just style
- but also to put this sentence at the top of the page: "Deploy your project in a few minutes with [Fly Launch](http://127.0.0.1:4567/docs/apps/). Then do more with [Fly Machines](http://127.0.0.1:4567/docs/machines/)."
Updates the title of "Fly Apps" section in Nav and the index page to "Fly Launch".
Links to changed pages:
https://aa-docs.fly.dev/docs/
https://aa-docs.fly.dev/docs/getting-started/
https://aa-docs.fly.dev/docs/speedrun/
https://aa-docs.fly.dev/docs/hands-on/ (and some sub-pages)
> Edits to Getting Started for Fly Launch terminology

- apps/deploy.html.md.erb
Must have missed this one when updating for redundant Machine creation on deploy. This PR updates the doc and adds links for more info. Also other minor updates/edits.
> Edit for number of machines on deploy

- litefs/getting-started-fly.html.md.erb
We removed `/docs/litefs/getting-started/` because it split into fly/docker getting started guides. This will redirect the old URL to the Fly getting started doc.
> Add docs/litefs/getting-started/ redirect

- litefs/cloud-backups.html.md.erb
The link in the docs failed. I updated with new url
> Fixed link to Litefs Cloud in Cloud Backup section

- reference/load-balancing.html.md
- reference/volumes.html.md.erb
This PR makes some minor changes to docs to remove the `maa` region from examples. More changes might be needed when flyctl updates.
> Adjust some docs for removal of maa region

- languages-and-frameworks/dockerfile.html.md.erb
This PR updates the doc about deploying with a Dockerfile to say that the image is built remotely by default. 
Instigated by this community post: https://community.fly.io/t/docker-build-doesnt-seem-to-be-using-local-docker/13854
Source: https://github.com/superfly/flyctl/pull/1080
> Update for remote builder as default

- machines/guides-examples/functions-with-machines.html.md.erb
- machines/guides-examples/machine-sizing.html.md.erb
- machines/working-with-machines.html.md.erb
- reference/machines.html.md.erb
- reference/machines/create_app.html.md
- reference/machines/create_app_req.html.md
- reference/machines/delete.html.md
- reference/machines/delete_app.html.md
- reference/machines/delete_app_req.html.md
- reference/machines/delete_req.html.md
- reference/machines/get.html.md
- reference/machines/get_app.html.md
- reference/machines/get_app_req.html.md
- reference/machines/get_app_resp.html.md
- reference/machines/get_req.html.md
- reference/machines/launch.html.md
- reference/machines/launch_req.html.md
- reference/machines/launch_syd_req.html.md
- reference/machines/lease.html.md
- reference/machines/lease_req.html.md
- reference/machines/list.html.md
- reference/machines/list_req.html.md
- reference/machines/start.html.md
- reference/machines/start_req.html.md
- reference/machines/stop.html.md
- reference/machines/stop_req.html.md
- reference/machines/update.html.md
- reference/machines/update_req.html.md
- reference/machines/wait.html.md
- reference/machines/wait_req.html.md
This PR replaces the `user-functions` example app name with `my-app-name` to make it obvious where the app name goes in a request. The examples are used in multiple places and users might enter the docs in the middle, so changing the name should help avoid confusion. 
Fixes:
#579
> Machines API and docs: replace example app name

- languages-and-frameworks/nuxtjs.html.md.erb
Alors we renamed Nuxt.js to Nuxt
> docs: update to use latest nuxt website

- litefs/disaster-recovery.html.md.erb
- partials/_litefs_nav.html.erb
I've added a guide to describe how to recover data from LiteFS Cloud in case you lose all the nodes in your cluster.
> Add disaster recovery documentation for litefs

- hiring/company-levels.html.md
- hiring/index.html.md
- hiring/roles.html.md
- partials/_devjobs_nav.html.erb
Our hiring docs are for more than just Engineering roles! Updating page titles and left nav to reflect that.
Left nav in the hiring docs now will link to the [company-wide Levels](https://fly.io/docs/hiring/company-levels/), rather than the [Engineering Levels](https://fly.io/docs/hiring/levels/). The Engineering Levels version of the page is still linked from the [Working at Fly.io](https://fly.io/docs/hiring/working/) page under the "Leveling" header, which adds extra specificity ("Our current engineering leveling looks roughly like:").
> Eng to company hiring docs

- reference/volumes.html.md.erb
This PR updates the volume reference docs with the "restartless volume extend" functionality. 
Related:
https://github.com/superfly/flyctl/pull/2513
https://community.fly.io/t/restartless-volume-extension/14130
https://github.com/superfly/flyctl/pull/2594
> Update doc for "restartless" volume extend

- getting-started/troubleshooting.html.md
This PR updates the troubleshooting doc:
- remove/rework some older content and update the structure
- add update flyctl (if autoupdate disabled) and `fly doctor` command
- add info about the new port/host warning message and update the host and port checking sections accordingly. See https://community.fly.io/t/flyctl-now-informs-when-an-app-is-not-listening-on-expected-address/12851.
- add sub headings to the port and host checking section so the user can pick and choose what to read
- add debug logging command
- put the log and ssh content into a "get more info" section
- updated and augmented the health checks section (stole a few things from here: https://community.fly.io/t/health-check-status-changes-now-appear-in-logs/11322)
> Update troubleshooting doc

- apps/scale-count.html.md.erb
- apps/volume-storage.html.md.erb
- reference/app-availability.html.md.erb
- reference/configuration.html.md.erb
- reference/volumes.html.md.erb
This PR mostly updates the docs for the `fly scale count` for Machines with volumes functionality, plus some further minor and semi-related edits:
- add a section the Scale the number of Machines doc for scaling Machines with volumes
- edit to the wording about the `scale` command to make things more explicit
- changed the app name in examples to `my-app-name`, which we used in the API docs
- add links to the mounts config from the volumes docs
- fix the formatting of the toml in the mounts examples in a bunch of places
- In the app resiliency doc:
- added an extra sentence or two about redundancy on first deploy technically meaning on first deploy or after scaling to zero (totally related to the purpose of this PR!)
- moved the bit about turning off redundant machines since it applies to …
> Update docs for scale with volumes +

- app-guides/continuous-deployment-with-github-actions.html.md
Otherwise the command fails with 
```
Error: invalid argument "9999999h" for "-x, --expiry" flag: time: invalid duration "9999999h"
```
> Remove extra `9` from duration

- getting-started/troubleshooting.html.md
This PR just updates the wording of an error to match what is output now.
> Troubleshooting: update wording of error to match reality

- reference/configuration.html.md.erb
- reference/services.html.md.erb
This PR adds some missing config options for `fly.toml`, like `proxy_proto_options`. and `default_self_signed` for `tls_options`. Also updated and slighlty re-arranged the connection handler info in the Public Network Services doc. 
Related: 
- https://github.com/superfly/flyctl/pull/2169
- https://github.com/superfly/flyctl/pull/2177
> Update fly.toml docs with missing config options

- app-guides/fauna.html.md
- app-guides/planetscale.html.markerb
Some image source URLs used relative paths but needed absolute paths instead.
> Fix broken images

- reference/configuration.html.markerb
This PR removes the `restart_limit` from the example for `http_service.checks`, since it's for V1 apps only.
> Remove restart_limit from http service checks example

- apps/autostart-stop.html.markerb
This PR clarifies defaults by splitting up the `Defaults and recommended values` section. Also includes minor edits to other areas. 
Preview: https://aa-docs-2.fly.dev/docs/apps/autostart-stop/
> Update auto start and stop to make defaults more clear

- app-guides/continuous-deployment-with-github-actions.html.md
- apps/deploy.html.markerb
- apps/launch.html.markerb
- apps/migrate-to-v2.html.markerb
This PR replaces "the app's root" with "project source directory" in a few key places where it might confuse some users. Plus a few other minor fixes to the Github actions doc.
> Replace app root with project source in some spots

- partials/_firecracker_nav.html.erb
- reference/sentry.html.md
This PR adds a documentation page for the partnership integration with Sentry.
> Add documentation for Sentry

- partials/_firecracker_nav.html.erb
- reference/sentry.html.md
This PR also fills out a section on framework-specific instrumentation for Ruby on Rails.
> Hide Sentry link until launch

- reference/private-networking.html.md
Adjust the wording so that this is clear. The current wording suggests that even stopped instances should be included. See [the community forum](https://community.fly.io/t/txt-instances-internal-seemingly-not-containing-all-apps/14924).
> `_instances.internal` reports only running instances

- reference/configuration.html.markerb
The `kill_timeout` maximum is 5 minutes now (as of April 2023).
> Update kill_timeout maximum

- apps/processes.html.markerb
- apps/scale-count.html.markerb
- apps/volume-storage.html.markerb
- elixir/the-basics/clustering.html.md
- hands-on/launch-app.html.markerb
- reference/regions.html.markerb
- reference/volumes.html.markerb
Add the `fly platform regions` command to the top of the region page.
Add more links to region info wherever the `-r` or `--region` flags are used, or sometimes for the first mention of regions.
> Add region command  + more links to region info

- app-guides/custom-domains-with-fly.html.md
Folks sometimes run into issues with Let's Encrypt [rate limits](https://letsencrypt.org/docs/rate-limits/) when adding custom domains to their Fly apps.
_Possibly_ related community posts:
https://community.fly.io/t/certificate-stuck-at-awaiting-certificates/6342/30
https://community.fly.io/t/delayed-awaiting-certificates/14628/2
https://community.fly.io/t/issuing-a-certificate-stuck-awaiting/8009
https://community.fly.io/t/generating-an-ssl-certificate-verified-but-rsa-or-ecdsa-never-generated/2303
When this happens, customer impact is high, but there is not much visibility on their end. This doc update provides some context on these limits and gives basic troubleshooting steps, as well as breaking the bad news that all you can really do after hitting these limits is _wait_.
The PR also …
> Let's Encrypt rate limits

- reference/configuration.html.markerb
The exec option is available in V2 and now it's in the docs. 
Suggested by: https://github.com/superfly/docs/pull/829
> Add exec option to experimental config section of fly.toml

- reference/services.html.markerb
Per: https://community.fly.io/t/tcp-idle-timeouts-restrictions-have-been-removed/15160
I have removed the whole paragraph, but open to adding _something_ in its place
> Remove TCP idle timeout restrictions

- litefs/events.html.markerb
- litefs/position.html.markerb
- partials/_litefs_nav.html.erb
This should be merged after we merge the related PR (https://github.com/superfly/litefs/pull/401).
> LiteFS event stream docs

- partials/_firecracker_nav.html.erb
Sentry is launching, so we're exposing the docs right before launch.
> Expose Sentry docs in the nav

- js/index.html.markerb
Sort of fixes https://github.com/superfly/docs/issues/975, so at least it doesn't 404.
We still need to figure out where "Try an Example" should link from the dashboard.
> Add redirect to Javascript docs

- apps/autostart-stop.html.markerb
I read in https://fly.io/docs/reference/configuration/#the-http_service-section 
that the default value for `auto_stop_machines` is `true` while this page conflicts that.
> Update conflicting default value

- reference/configuration.html.markerb
After asking here to make sure: https://community.fly.io/t/i-am-confused-on-why-port-is-an-integer-and-then-a-string-in-services-ports-example/15385
> Some ports were strings, I made them integers.

- app-guides/edgedb.html.md
Currently on latest v0.1.77 I get
```
Error: vm size "dedicated-cpu-1x" is not valid
```
> Update edgedb guide for v2 machines

- reference/configuration.html.markerb
- reference/metrics.html.md
superfly/flyctl#2825 adds support for `metrics` per process group.
Update documentation with examples of the updated syntax:
> Custom metrics can be also configured for specific `processes`, using double brackets to define multiple `[[metrics]]` tables:
> ```toml
> [[metrics]]
>   port = 9394
>   path = "/metrics"
>   processes = ["web"]
> 
> [[metrics]]
>   port = 9113
>   path = "/metrics"
>   processes = ["proxy"]
> ```
> Custom metrics config per process group

- reference/app-availability.html.markerb
- added a few more scenarios to the "turn off ha" section, since it implied that you could just run `fly deploy --ha=false`, but for existing apps, you need to scale down first
- https://community.fly.io/t/ha-false-command-still-starts-two-machines/15486
- https://community.fly.io/t/fly-log-shipper-sends-every-log-twice/15284/2?u=andie
> Clarify the ha flag usage to get only one Machine

- machines/guides-examples/machine-restart-policy.html.markerb
- partials/_firecracker_nav.html.erb
- Added a doc to the Machines section about Machine restart policies
- Added some examples
Source info: https://community.fly.io/t/issues-with-machines-restart-policy/11943/25?u=andie
n/a
> Add machine restart policy doc

- apps/migrate-to-v2.html.markerb
- machines/guides-examples/machine-restart-policy.html.markerb
- update the link from the migrate to V2 page to the restart policy doc
- remove the front matter tag from the restart policy doc that excluded from the sitemap (oops) 
https://github.com/superfly/docs/pull/1043
n/a
> Update link to machine restart policy doc

- reference/runtime-environment.html.md
Adds entries for several previously-undocumented environment variables to `/docs/reference/runtime-environment/`.
https://github.com/superfly/docs/issues/957
n/a if none
> Add env descriptions to docs

- litefs/faq.html.markerb
Adds details about LiteFS availability during deploys per a discussion on Twitter with @bradgessler.
n/a if none
n/a if none
> LiteFS FAQ: Are LiteFS deploys zero downtime?

- reference/configuration.html.markerb
fly.toml ref: add how to remove a Machine file
https://community.fly.io/t/files-removed-from-fly-toml-persist-in-the-apps-vm-after-deploy/15582
https://github.com/superfly/flyctl/issues/2851
> fly.toml ref: add how to remove a Machine file

- reference/volumes.html.markerb
Added the necessary url to the href that points to the correct doc. Located on this page-`/docs/reference/volumes/`
#1067
n/a if none
> Added the necessary url that points to the correct doc

- app-guides/smokescreen.html.erb
Update incorrect url to example repo for using Smokescreen
n/a
n/a
> Fix smokescreen example url in smokescreen.html.erb

- partials/_obsolete_doc.html.erb
- Apply the warning icon callout style to the "old document" notice partial. The rationale to use a warning is that we don't know what could happen since these old docs aren't tested.
n/a
n/a
> Update the obsolete warning to use warning callout style

- laravel/the-basics/laravel-volume-storage.html.markerb
Removal of remaining mention of "instances" in the Laravel "Persisting the Storage Folder" page
n/a if none
n/a if none
> Clean instances keyword from laravel storage page

- styles/proselint/Cliches.yml
Thought I had already done this by commenting it out, but `#` didn't work. 😭  Deleted it this time.
n/a
n/a
> Vale: Remove "for free" from cliche list

- about/pricing.html.markerb
Fixes a link for LiteFS Cloud docs other pricing page.
n/a
n/a
> Fix LiteFS Cloud link

- apps/volume-manage.html.markerb
- reference/volumes.html.markerb
The default volume size is 1GB, not 3GB when you get new volumes via the `fly launch` command. It's 3GB when you run 'fly vol create`. 
https://github.com/superfly/flyctl/issues/2868
n/a
> Update volume default size info

- reference/configuration.html.markerb
In Fly launch config page > build section > dockerfile, put the gotchas with the dockerfile setup in a callout.
https://fly.io/docs/reference/configuration/#specify-a-dockerfile
Before: 
After:
> In Fly launch config page > build section > dockerfile, put the gotchas with this setup in a callout.

- reference/configuration.html.markerb
Updates the Fly Launch config reference. With the resolution of https://github.com/superfly/flyctl/issues/2851, deleting the `[[files]]` entry in fly.toml that added the files to the Machine config is sufficient to remove them on the next `fly deploy`. 
Also because we've got the Vale linter set up to make a small set of suggestions, I took the chance to clean up some capitalization in the existing doc. We'll get fewer suggestions on the next PR.
> update how to remove 'machine files' on next deploy

- getting-started/app-services.html.md
Change `(c)` to `(&#99;)` so it doesn't turn into a copyright symbol (&copy;). This is a simpler fix for now, since we can't turn this substitution off without messing up others.
n/a
n/a
> fix c so it's not a copyright symbol

- styles/Vocab/Fly-terms/accept.txt
Add Ruygt to linter accept list, so Vale doesn't think it's a typo. (It's in some alt text for an image)
> Add Ruygt to linter accept list

- getting-started/index.html.md
Quick-and-dirty interim tweak to make a migration doc more visible
> link Rails migrate-from-heroku guide from Getting Started landing

- django/getting-started/index.html.md
This changes a command prompt for a Windows snippet about activating virtual environments:
- changed a command prompt from `$` to `>`
- changed `activate` to `Activate.ps1` and made it explicit that it's a snippet for PowerShell
- changed style from `shell` to `powershell` to fix rendering
- removed trailing `$` from a callout as it seems unnecessary and is not correct for Windows users. 
Before:
After:
> Improve command prompt for Windows snippet in Getting Started docs for Django.

- gpus/gpu-quickstart.html.markerb
Add the GPU quickstart provided by the GPU team, with some edits to format and order of steps.
n/a
@catflydotio What do you think of the url gpus/gpu-quickstart/? For now, it's hidden from the nav. Should it be visible yet?
> Add GPU quickstart guide

- postgres/managing/forking.html.markerb
Add a new doc about volume forks and the `--fork-from` option for the `fly pg create` command to the Postgres docs.
- https://community.fly.io/t/fork-yeah-new-volume-forking-feature-for-postgres/12390
- #1108 
n/a
> Add Postgres volume fork doc

- apps/volume-manage.html.markerb
- reference/volumes.html.markerb
Add info about the volume forks and the `fly vol fork` command to volumes docs.
TODO: Postgres docs for forking in another PR
- https://community.fly.io/t/fork-yeah-new-volume-forking-feature-for-postgres/12390
- #1109 
n/a
Added to https://fly.io/docs/apps/volume-manage/
Added to https://fly.io/docs/reference/volumes/
> Add volume fork docs

- partials/_flyctl_nav.html.erb
Adds `litefs-cloud` to the nav for `flyctl` autogenerated docs.
- https://github.com/superfly/flyctl/pull/2786
- The actual docs themselves were automatically generated by the `flyctl` release.
> Add litefs-cloud to flyctl nav

- elixir/advanced-guides/sqlite3.html.md
The sequel command, to transform a PostgreSQL database to SQLite will error with:
`Error: Sequel::AdapterNotFound: LoadError: cannot load such file -- sequel/adapters/sqlite3`
That's because the adapter for sequel is called `sqlite` instead of `sqlite3`.
n/a if none
n/a if none
> Fix `sequel` command to transform PostgreSQL to SQLite

- postgres/managing/scaling.html.markerb
Fixes a broken link in the postgres docs
n/a
n/a
> Posgres docs: fix broken link 

- partials/_back_to_docs.html.erb
- partials/_flyctl_nav.html.erb
- partials/_hands_on_nav.html.erb
- partials/_litefs_nav.html.erb
A potential temporary solution to feeling stranded on pages that replace the main docs sidebar. This PR adds a partial that renders a link back to fly.io/docs, which can be included in any of our "special" sidebars. The hands-on, litefs and flyctl menus are changed to include this link.
I'll PR the Landing repo one-liner to incorporate this in each of the frameworks layouts.
Obvious compromises: 
* the link isn't a list item because I didn't see a way to override some styles on the "outline-list" class, like the triangle marker on hover -- I suspect this is not super for navigating by keyboard
* it's not big and nice-looking
Check the effect at https://justchecking.fly.dev/docs/elixir/getting-started/ for example
> Back to docs link for special sidebars

- flyctl/index.html.md
- js/frameworks/svelte.html.markerb
- languages-and-frameworks/crystal.html.markerb
- languages-and-frameworks/dotnet.html.markerb
- languages-and-frameworks/golang.html.markerb
- languages-and-frameworks/ruby.html.markerb
- languages-and-frameworks/static.html.markerb
- rails/cookbooks/minimal.html.markerb
- Change `flyctl open` to `flyctl apps open`
- Fix 404 link to /docs/flyctl/open/
- Remove notes about HTTPS auto-upgrade
Also, removed /name from golang example since the
example repo doesn't actually handle the /name path.
n/a if none
n/a if none
> Replace instances of deprecated open command

- about/pricing.html.markerb
- about/support.html.md
- update the email support info slightly so it doesn't imply that the Hobby plan gets email support
- added a line about host-level issues being in the dashboard (i.e. not the status page)
- fix typos
- minor edits and formatting
n/a
n/a
> Support + Pricing pages: update email support and other edits

- apps/legacy-scaling.html.markerb
> Remove turboku reference from legacy-scaling.html.markerb

- reference/configuration.html.markerb
https://github.com/superfly/flyctl/pull/2961
Feedback, fixes and rewording much welcome 🤟
> Document new fly.toml deploy timeouts

- reference/configuration.html.markerb
* https://github.com/superfly/flyctl/pull/2961/files#diff-4251d8215f73cf413b3febd989c9853c5c6d80d94c5b8ced61697ff05c8e563fR27
* https://github.com/superfly/docs/pull/1133
n/a if none
> the default is 5 minutes now

- apps/launch.html.markerb
This is one tiny step on the way to phasing out web launchers.
> hiding web launchers: redirect /launch to docs/apps/launch for now

- apps/scale-count.html.markerb
Added a notice contrasting app scale, i.e. Machine creation and destruction, with Machine stop and start. Fast capacity changes should be accomplished by starting and stopping Machines.
> app scale doc: stop-start is faster than destroy-create for capacity

- machines/guides-examples.html.md
- machines/guides-examples/functions-with-machines.html.markerb
- machines/guides-examples/machine-restart-policy.html.markerb
- machines/guides-examples/machine-sizing.html.markerb
- machines/guides-examples/machines-app-using-flyctl.html.markerb
- machines/guides-examples/terraform-machines.html.markerb
- machines/index.html.md
- machines/working-with-machines.html.markerb
- partials/_firecracker_nav.html.erb
- partials/_machines_nav.html.erb
- add a new nav for Machines docs
- add link to API spec to nav
- format a callout
- update the feature recap list
- fix some formatting
n/a
n/a
> Machine docs: new nav + formatting + feature recap

- reference/volumes.html.markerb
Like it says on the tin! Fix a missing space in the volumes documentation.
n/a
n/a
> fix missing space in volumes documentation

- reference/configuration.html.markerb
An h4 should have been an h3 and that was messing up the right side nav output. Also fixed typo.
n/a
n/a
> Change h4 to h3

- apps/deploy.html.markerb
- laravel/the-basics/customizing-deployments.html.md
In some places that we mention release_command machines, make a note about it not having access to volumes.
https://community.fly.io/t/using-sqlite-from-persistent-volume-for-django-application/16206/3
n/a
> release_command VMs don't have access to volumes

- apps/index.html.markerb
Edited the landing page for Fly Launch (formerly known as Fly Apps V2) to identify Fly Launch as something other than a "PaaS product," and moved up the sentence pointing out you don't have to use it to run Machines.
> Don't call Fly Launch PaaS

- .vale.ini
the proselint cliche rule is erroring on a phrase that was removed in previous pr which is super suspicious
going to turn off that rule for now
n/a
n/a
> Vale: rm weird cliche rule that's erroring

- litefs/events.html.markerb
Per #1148, the link to ndjson.org is no longer valid. Removed for now. Unless @benbjohnson has a replacement?
Also fixed the links to the position and primary pages.
n/a
n/a
> Fix links on LiteFS reading event stream page

- apps/scale-machine.html.markerb
Recent flyctl versions need vm- prefixes for these args
Pulled from flyctl 0.1.117 help
> Use correct command line flags for recent versions of flyctl

- apps/legacy-scaling.html.markerb
- apps/scale-machine.html.markerb
- machines/guides-examples/machine-sizing.html.markerb
- postgres/managing/scaling.html.markerb
- rails/advanced-guides/anycable.html.md
Machine flags for cpu, memory, and size are prefixed by `--vm-` per https://github.com/superfly/flyctl/pull/2323
n/a
n/a
> Update machine flags

- app-guides/livebook.html.markerb
Adds a deployment guide for Livebook which we can use to replace the web launcher
> add a deployment guide for Livebook

- gpus/gpu-quickstart.html.markerb
Document which regions GPUs are available in as well as the fact that volumes need to be created with the same constraints as machines.
> gpus/gpu-quickstart: document constraints of GPUs in their current form

- gpus/gpu-quickstart.html.markerb
- fix indenting so that numbering doesn't restart
- tried indenting the codeblock within a <div> notice, but it just changed into into code format, which I think is fine in this case
n/a
n/a
> GPU quickstart: tiny format fixes

- about/pricing.html.markerb
- add GPU pricing
- change title of "Apps V2 and Machines" to "Fly Machines"
- remove V1 compute pricing
- update link to new billing page
https://community.fly.io/t/fly-gpus-are-here/16110
n/a
> Add gpu pricing

- app-guides/livebook.html.markerb
Just clarify that 1GB is the default size of a volume created by `fly deploy`, because with `fly vol create` the default is 3GB
> Vol default is 1GB at fly deploy, though not on vol create

- litefs/config.html.markerb
Adds the subcommand to the `-config` example.
Fixes https://github.com/superfly/docs/issues/1155
n/a if none
> Fix litefs -config flag usage

- app-guides/minio.html.markerb
Refresh and extend the MinIO app guide with instructions for setting up a multi-node deployment.
- https://community.fly.io/t/appkata-minio-s3-compatible-storage-with-fly/389
- https://community.fly.io/t/using-fly-for-file-storage/8299/
I've omitted some steps that would repeat things written earlier, e.g. I don't have a section saying run `fly launch ...` or `fly secrets set MINIO_ROOT_USER=...`. Happy to add that in though if preferred.
> MinIO multi-node deployment

- apps/trouble-host-unavailable.html.markerb
- getting-started/troubleshooting.html.md
- partials/_firecracker_nav.html.erb
- add a doc with steps to take to try to recover non-HA apps from hosts with issues
n/a
n/a
> Add host down troubleshooting doc

- reference/configuration.html.markerb
* https://github.com/superfly/flyctl/pull/3041
* https://github.com/superfly/flyctl/pull/3016
n/a if none
> Document [[vm]] configuration section

- hands-on/launch-app.html.markerb
Changed the launch page for Hands-on to use the default launch UI experience. 
https://github.com/superfly/flyctl/pull/2956
n/a if none
> Update hands-on for launch UI

- machines/run.html.md
- partials/_firecracker_nav.html.erb
- partials/_machines_nav.html.erb
New doc about using `fly machine run`, and nav entries in firecracker and machines sidebar partials
Removes old "run machines with flyctl" from main nav. Should make all the info in there exist elsewhere in docs before actually deleting
> A usage doc for fly machine run

- machines/guides-examples/functions-with-machines.html.markerb
- machines/working-with-machines.html.markerb
- reference/machines/_create_req.erb
- reference/machines/_create_resp.erb
- reference/machines/_delete_req.erb
- reference/machines/_delete_resp.erb
- reference/machines/_get_req.erb
- reference/machines/_get_resp.erb
- reference/machines/_launch_req.erb
- reference/machines/_launch_resp.erb
- reference/machines/_lease.erb
- reference/machines/_lease_req.erb
- reference/machines/_lease_resp.erb
- reference/machines/_list_req.erb
- reference/machines/_list_resp.erb
Take some Machines API content (from @ tqbf)  and meld it into the existing [Operations on Machines](https://fly.io/docs/machines/working-with-machines/#operations-on-machines) section of the api docs. Including:
- update some response examples
- add some intro content
- add missing params
- add endpoints for all sections
Plus:
- create some tables for some parameters/properties
- compare both docs and specs and add missing params and descriptions
- add some example requests
Todo:
n/a if none
n/a if none
https://aa-docs.fly.dev/docs/machines/working-with-machines/
> API docs: Machines resource updates

- reference/configuration.html.markerb
Typo fix for A100-SXM4-80GB GPU kind
n/a if none
n/a if none
> Fix gpu model name

- elixir/the-basics/clustering.html.md
- the process changed with newer Phoenix releases
- the `rel/env.sh.eex` file should be checked (for older Phoenix versions), but it shouldn't need changes.
- updated explanation of how the node is named
n/a if none
n/a if none
> update elixir clustering docs

- machines/working-with-machines.html.markerb
- reference/configuration.html.markerb
- reference/volumes.html.markerb
Add info about auto extending volumes to:
- fly.toml config
- Machines API docs
- volumes overview
https://community.fly.io/t/auto-extend-volume-size-after-a-certain-threshold/16326
https://community.fly.io/t/auto-extend-volumes-fly-toml-edition/16558
https://github.com/superfly/flyctl/pull/3021
n/a
> Add auto extend volumes to docs

- about/pricing.html.markerb
Remove a symbol leftover from a previous PR that removed the note it pointed to . oops.
n/a
n/a
> Remove leftover symbol from pricing page

- reference/configuration.html.markerb
> Fix markdown link

- reference/runtime-environment.html.md
I was helping someone try to troubleshoot what was going wrong with their multi-region deployment in the community forum and realized that we set `PRIMARY_REGION`, but it wasn't documented in the env vars section.
Now it is!
https://community.fly.io/t/region-changes-erratically-cant-set-permanent-region/16488/8
n/a if none
> Add PRIMARY_REGION to documented env vars

- about/pricing.html.markerb
Add some links from the pricing page to the new billing page
n/a
n/a
> Add links from pricing to billing

- django/getting-started/index.html.md
This removes a step with a new app creation and updates `flyctl` outputs.
> Simplified getting started docs for Django.

- about/pricing.html.markerb
Current title is "Fly App Pricing" -- apps are neither here nor there, and there's also plan pricing on a different page, so I'm proposing "Fly.io Resource Pricing"
n/a 
n/a
> Rename pricing page

- reference/configuration.html.markerb
oops the field description referred to itself instead of its companion field
n/a
n/a
> Fix wrong field name

- gpus/getting-started-gpus.html.md
- gpus/gpu-quickstart.html.markerb
- gpus/index.html.md
- gpus/python-gpu-example.html.md
- partials/_firecracker_nav.html.erb
* Added a section for GPUs in the main docs sidebar
* Added a docs index page for GPUs (which would get nicer card-style links to content when we start doing cards in docs)
* Wrote up some practical observations in a Getting Started with Fly GPUs doc
* Stole some material from the GPU Quickstart doc for the Getting Started doc, but did not yet massage the Quickstart to tidy things up.
* Adapted, fairly roughly, the README from my [Python example repo](https://github.com/fly-apps/python_gpu_example) into an example doc.
> C gpu docs 2

- app-guides/continuous-deployment-with-github-actions.html.md
In the speed-run section FLY_API_TOKEN is created in the step 5 but being referenced as created in step 4.
Change the number
> Typo in Continuous Deployment with GitHub

- reference/configuration.html.markerb
The h3 section about the `wait_timeout` key has is logically about the `[deploy]` section, but falls under the h2 for the `[env]` section. This moves the h3 to be under the `[deploy]` h2.
n/a if none
n/a if none
> Move config.toml wait_timeout section with deploy

- retired-launcher.html.md
Adds a page we can redirect former ui-ex single-app launchers' urls to
Preview https://justchecking2.fly.dev/docs/retired-launcher/
> Add a page to redirect retired web launchers to

- machines/guides-examples/machine-restart-policy.html.markerb
- machines/run.html.md
- update the run a Machine doc to clarify that the `--rm` option destroys the Machine. And that the default restart policy for Machines created with `--rm` is `no`.
- update the restart policy doc for same
https://github.com/superfly/flyctl/pull/3086
n/a
> Update docs for --rm option restart policy defaults

- caching/full-stack.html.md
- partials/_firecracker_nav.html.erb
- rails/cookbooks/node.html.markerb
Changed Javascript/javascript typo to JavaScript
n/a
n/a
> fix Javascript/javascript --> JavaScript case typo

- postgres/advanced-guides/high-availability-and-global-replication.html.markerb
Mention that when doing a regional failover the top-level primary_region must be set - this was noted by a support customer and we verified this experimentally.
n/a
On tests, if only the environment variable is set, then failover doesn't happen at all.
> Update docs on regional failover - set top-level primary_region as well

- about/pricing.html.markerb
We now have L40S cards. This change adds a line to our pricing page for them.
> pricing page: add L40S pricing

- apps/launch.html.markerb
Add statement to clarify that app names need to be unique across all of Fly. Not immediately obvious to newcomers and launch can fail in weird/unexpected ways.
> Clarify app name needs to be unique

- reference/runtime-environment.html.md
I think these docs have moved to their own page.
Fix link to 6PN naming docs page.
> Fix broken link to private networking docs

- laravel/advanced-guides/using-inertia-ssr.html.md
As seen in https://github.com/superfly/flyctl/pull/2962
> Bump PNPM from 7 to 8

- reference/services.html.markerb
Adds instructions for changing from a paid dedicated ipv4 address to a shared one
Adapted from @jeromegn's instructions at  https://community.fly.io/t/we-are-going-to-start-charging-for-dedicated-ipv4-in-january-1st/15970/24
With the switch-on of actual billing for paid IPv4, there's a lot of interest in switching to free shared IPv4 addresses
> add instructions to switch to shared ipv4

- apps/volume-storage.html.markerb
- reference/configuration.html.markerb
Add a callout in the two sections discussing `[mounts]` config to explain that you can't use `destination="/"`.
https://community.fly.io/t/cant-create-a-volume-for-the-entire-filesystem/17553?u=jfent
n/a
> Add callouts explaining that volumes can't be mounted at `/`

- app-guides/custom-domains-with-fly.html.md
- apps/custom-domain.html.markerb
- reference/services.html.markerb
When an app uses shared IPv4, Fly Proxy needs an SSL cert to know which app to route a custom domain address to, even if HTTPS isn't used. This PR adds this info to:
* https://fly.io/docs/reference/services/ (instructions for moving to shared ipv4)
* https://fly.io/docs/apps/custom-domain/
* https://fly.io/docs/app-guides/custom-domains-with-fly/
Also did minor cleanup and corrected out-of-date statement that allocating shared IPv4 would fail if dedicated IPv4 was present.
https://community.fly.io/t/new-shared-ipv4-connection-reset-by-peer/17567
> Shared IPv4 needs a cert for custom domain

- apps/deploy.html.markerb
Add a note to the Machines not managed by Fly Launch section of the Fly Deploy doc about not being able to deploy after scaling to zero when an app has a mixture of Fly Launch-managed and unmanaged Machines.
https://github.com/superfly/flyctl/issues/2867
n/a
> add a note about mixed machines in one app

- reference/configuration.html.markerb
> Remove nomad references in service.concurrency section

- app-guides/udp-and-tcp.html.markerb
One of our customers at the community forum wanted to use UDP over 6PN for app communication, and was confused about it working over 6PN or not as UDP services do not IPv6.
https://community.fly.io/t/internal-app-to-app-or-machine-to-machine-udp-communication/17533
n/a
> Update UDP service doc to include the IPv6 rule does not apply to 6PN

- flyctl/index.html.md
current link 404's.
`fly releases` should be enough.
> fly history is a deprecated command

- flyctl/cmd/flyctl_tokens_create_org.md
Adds a `-o` flag to `fly tokens create org` so that this command can be run non-interactively.
- https://github.com/superfly/flyctl/pull/3181
n/a
> Document addition of --org flag to `fly tokens create org`

- flyctl/cmd/flyctl_tokens_create_org.md
Reverts superfly/docs#1288
docs are generated automatically!
> Revert "Document addition of --org flag to `fly tokens create org`"

- partials/_flyctl_nav.html.erb
a few of our doc pages in the sidebar no longer exist: https://fly.io/docs/flyctl/
so we might as well remove the links.
> regions, monitor, vm no longer have doc pages

- elixir/advanced-guides/interesting-things-with-livebook.html.md
Update the link so it points to the page it's titled for ;)
Head to https://fly.io/docs/elixir/advanced-guides/interesting-things-with-livebook/ and see this link isn't pointing to the page getting LiveBook connected to your app on Fly.
n/a if none
n/a if none
> Update link for connecting LiveBook to your app on Fly

- reference/extensions_api.html.md
Org email aliases never worked, so should not be documented.
> Remove org email alias from extension API provisioning requests

- reference/extensions_api.html.md
Webhooks are now encoded as [CloudEvents](https://github.com/cloudevents/).
> Update spec for extension outbound webhooks

- apps/deploy.html.markerb
This warning about not being able to deploy your app is no longer applicable as of:
https://github.com/superfly/flyctl/pull/3184
https://github.com/superfly/flyctl/pull/3184
n/a if none
> Remove warning about mixing launch + unmanaged machines

- machines/index.html.md
- machines/overview.html.markerb
- partials/_firecracker_nav.html.erb
- partials/_machines_nav.html.erb
- volumes/index.html.markerb
- Move the Machines summary from the Machines nav index to a Machines overview page, since the index might be entirely missed
- Add a Machines landing page as the index page
- Add "fast-launching VMs"
- minor word changes
**Preview:** https://aa-docs-2.fly.dev/docs/machines/
n/a
n/a
> Add Machines landing page

- apps/autostart-stop.html.markerb
The previous copy was confusing:
> The `min_machines_running` value applies to the total number of Machines, not Machines per region. 
This could be interpreted as meaning 'total number of machines across all regions'.
> Clarify that min_machines_running doesn't apply to non-primary regions

- about/pricing.html.markerb
* new orgs go on paid hobby plan
* sign-up credit for new customers before paid subscription starts
* nothing changes for orgs on existing free hobby plan
At the moment there's a preview at https://justchecking2.fly.dev/docs/about/pricing/
> pricing page: rework plans section for new accounts on paid hobby

- machines/index.html.md
- machines/overview.html.markerb
- machines/working-with-machines.html.markerb
- partials/_firecracker_nav.html.erb
- partials/_machines_nav.html.erb
- volumes/index.html.markerb
Changing old backlinks to point to the new scalar docs - a move towards further deprecating the old [swagger](https://docs.machines.dev/swagger/index.html) docs
> Point to fancy API docs

- postgres/managing/backup-and-restore.html.markerb
Adding a minor update to the instructions to restore a Postgres snapshot. There was a post in the community forum from an user getting an error creating a new Postgres app by restoring from a snapshot.
The problem was the size for the provisioned volume for the new Postgres app being smaller than the original volume.
https://community.fly.io/t/restoring-postgres-snapshot-fails-restore-volume-size-must-be-at-least-10gb/17937
n/a
> Minor update to Postgres snapshot restore

- app-guides/mysql-on-fly.html.markerb
- moved specifying the image to the `fly launch` command
- removed the bit about the bug in 8.0.33
- added steps re: the launch UI
- moved the bit about scaling memory to the launch UI step (a user noticed that you could not use `fly scale` before the first deploy)
- other minor edits
- https://community.fly.io/t/scaling-memory-does-not-seem-to-work/6764/14
n/a
> Updates to mySQL doc

- reference/fly-launch.html.md
Added missing dash to `fly launch --no-deploy` mention.
n/a if none
n/a if none
> Fix typo on fly-launch.html.md

- about/billing.html.markerb
- about/pricing.html.markerb
- Add a section on Plan billing to the Billing page to clarify that we charge for monthly plans immediately on org creation from an existing account. With the exception of brand new customers with a signup credit.
- Swap the order of Machine billing and Volume billing sections.
- Change RootFS to rootfs.
- https://community.fly.io/t/i-got-charged-today-for-the-hobby-plan-and-im-confused-as-to-why-cause-fly-io-didnt-send-any-emails/17969
n/a
> Add a section on plan billing

- reference/volumes.html.markerb
Fixes the link that redirects to https://fly.io/docs/apps/volume-manage/#create-a-volume-snapshot in https://fly.io/docs/reference/volumes/#volume-snapshots
n/a 
n/a
> Fix the broken "create a snapshot of a volume" link in /reference/volumes page

- reference/index.html.md
Quick adjustment; this page needs TLC
Changed description of apps 
Moved Machines up to top of deploying section
Tweaks
> Reference index: Apps aren't about Fly Launch

- litefs/proxy.html.markerb
Adds a disclaimer to the LiteFS documentation.
Related to https://github.com/superfly/litefs/issues/427
n/a if none
> Document LiteFS WebSockets limitation

- languages-and-frameworks/golang.html.markerb
Updated to latest `flyctl` usage + `fly.toml` format (it was old!)
Prompted by https://github.com/superfly/flyctl/pull/3263, which uses a Dockerfile for `go` instead of a buildpack.
> Golang guide modernized + dockerfile over buildpack

- app-guides/supercronic.html.md
- postgres/managing/upgrades.html.markerb
Updated the Postgres upgrade doc which referenced old pre-flex images/apps.
Added a note for those hoping to upgrade to Flex (you can't use the `fly image update` command for that).
Fixes #1269 
n/a if none
> Update Postgres upgrade doc for Flex

- js/frameworks/astro.html.markerb
- languages-and-frameworks/partials/_scanner_guides.html.erb
Added documentation for running an Astro site on Fly.
n/a if none
n/a if none
> Add Astro site docs

- apps/scale-machine.html.markerb
- machines/guides-examples/machine-sizing.html.markerb
- add a link to Scale CPU and RAM doc to Machine sizing doc
- update Scale CPU and RAM doc with precedence info and links to `[[vm]]` section in `fly.toml`
- re-org for the different ways of configuring Machine sizes
- review both for general updates
https://community.fly.io/t/auto-scale-machine/18242
n/a
> Update Machine scale docs for fly.toml vm settings

- app-guides/continuous-deployment-with-github-actions.html.md
Updated Doc to use `actions/checkout@v4` was `actions/checkout@v3`
**NOTE:** instructions on https://github.com/marketplace/actions/github-action-for-flyctl are still set to use `v2`
> Updated GHActions doc to use actions/checkout@v4

- machines/api-machines-resource.html.markerb
- machines/flyctl/fly-machine-run.html.md
- machines/flyctl/fly-machine-update.html.md
Fix the links I broke and promised to fix when I changed the name of the config object descriptions table multiple times.
> Fix links to config object section

- index.html.md
Replaces paragraphs with quick sections and links to things we want a better path in for. These changes are a start, and can be refined. Would go well with some card-like styling, which can be addressed later. Our css is complex enough now that a hacky version of that makes quite a mess
That said, this does work better with bigger, bolder links, which is getting a PR in the landing repo.
> Quick fix for docs landing

- index.html.md
- machines/api/apps-resource.html.markerb
- machines/api/index.html.md
- machines/api/machines-resource.html.markerb
- machines/api/volumes-resource.html.markerb
- machines/api/working-with-machines-api.html.markerb
- machines/overview.html.markerb
- partials/_firecracker_nav.html.erb
- partials/_machines_nav.html.erb
- reference/apps.html.markerb
- Add a Machines API index page
- Create an `api` directory
- rename files
- redirect "working with machines" to new index page
https://aa-docs.fly.dev/docs/machines/api/
> API docs: add machines api index, add dir, rename files

- django/getting-started/index.html.md
- machines/runtime-environment.html.md
- networking/request-headers.html.md
- networking/services.html.markerb
- partials/_firecracker_nav.html.erb
- reference/configuration.html.markerb
- reference/index.html.md
- reference/regions.html.markerb
- reference/runtime-environment.html.md
Splits the current runtime environment doc into one doc on environment variables and another doc on http request headers.  Makes several corrections and clarifications.
> Put http headers and env vars into separate pages

- machines/api/machines-resource.html.markerb
Put the escapes back into the uncordon item; I predict that item will show extra backslashes but the previous changes made all the escapes show up in the page.
> better one item with extra escapes than all

- machines/index.html.md
- machines/runtime-environment.html.md
- partials/_machines_nav.html.erb
Add the new Machines runtime environment doc to the Machines nav and landing page.
@catflydotio I think this belongs in reference in the nav. And the way the landing page is now, I thought it best under Learn along with the machines state reference. Feel free to suggest changes!
#1385
> Add machines runtime env doc to machines nav and landing

- partials/_hands_on_nav.html.erb
Missing forward slash at start of hands-on relative link in the hands-on nav partial was 404ing with a compound url
> Missing slash was causing weird 404

- reference/configuration.html.markerb
Re-tested this behaviour, and as indicated in https://fly.io/docs/apps/autostart-stop/#default-values, the default for `auto_stop_machines` is `false` when not set in `fly.toml`.
#1394
> Correct the auto stop default in fly.toml reference

- reference/configuration.html.markerb
- add a link from the `[[vm]]` section to https://fly.io/docs/apps/scale-machine/#machine-size-configuration-precedence
- re-org the intro for easier reading including "ways to get a fly.toml file"
- replace "instances" and "VMs" with Machines
> fly.toml doc: Add a link to Machine config precedence, edit intro, use Machines

- hands-on/install-flyctl.html.markerb
Forgot to change the "Next" link to the new Sign Up/ Sign In page, which is sort of okay since the link still went to a page that described how to Sign up and Sign In. But bothered me enough to fix on a Saturday.
> Fix link to Hands-on: Sign Up/Sign In page

- about/billing.html.markerb
- about/pricing.html.markerb
- machines/api/machines-resource.html.markerb
- machines/guides-examples/machine-sizing.html.markerb
- Reword "sign-up credit" to "free trial credit". 
- Put important info about plans and usage into the How it works section at the top of the page. 
- Link to plans more prominently.
- Rename "New customers" to "New customers get a free trial".
- Re-word, re-org the New customers and Plans sections/
- Add headings to Compute section since the rootfs was kind of buried: "Running Fly Machines" and "Stopped Fly Machines"
| Before | After |
| --- | --- |
| ![Screenshot 2024-03-08 at 12 44 08 PM](https://github.com/superfly/docs/assets/13827355/18ffb9f6-3be0-4265-90ea-a76a0666a02d) | ![Screenshot 2024-03-08 at 12 43 37 PM](https://github.com/superfly/docs/assets/13827355/99d2c812-95ed-45dd-a7db-7b498139f60d) |
https://aa-docs.fly.dev/docs/about/pricing/
> Pricing: updates about free trial and add headings for compute

- gpus/getting-started-gpus.html.md
- gpus/gpu-quickstart.html.markerb
- gpus/index.html.md
- gpus/python-gpu-example.html.md
- created a new section "Regions with GPUs" on the landing page, so it can be linked to (regions are in three places now which is fine/good, but probably should be a partial at some point)
- gave the volume content a heading in the Quickstart so people know whether they need to follow it
- added external icons to external links
- fixed a broken link
- fixed a typo
> GPU docs: minor edits/updates

- apps/restart.html.markerb
- partials/_firecracker_nav.html.erb
- `fly apps restart` does not restart unmanaged Machines
- minor fixes to nav while in there
> Correct fly apps restart info

- machines/api/apps-resource.html.markerb
- networking/services.html.markerb
- add notes that if you created your app through flyctl or API, you don't get IP addresses automatically allocated
- add `fly.toml` snippets to handler sections
- rename handler sections to include the word "handler"
- add a section to handlers specifically about configuration
- add a list of some of the reasons to use a dedicated IPv4 address
- formatting
https://aa-docs-3.fly.dev/docs/networking/services/
https://community.fly.io/t/confusing-docs-regarding-alpn/18684
> Public Networking doc: update handlers with examples + update IP address allocation info

- networking/app-services.html.md
Added a table column title that hopefully works. Table headers with empty columns get ignored as though they aren't even there, which means the column headings are in the wrong column.
> Add table column title because empty column headers get ignored

- networking/services.html.markerb
You need to release the "old" IPv4 address when you allocate a new one; either dedicated -> shared or shared -> dedicated.
https://community.fly.io/t/what-happens-when-you-allocate-a-ipv4-address/18790
> release ip

- networking/app-services.html.md
- networking/private-networking.html.md
- petty much rewrote the Fly.io .internal addresses section, to clarify how to use them and what they return
- added a note about .internal hostnames not returning info on stopped Machines
- rewrote all the TXT and AAAA descriptions in the table for clarity about what is actually returned on query
- re-organized the Provate network VPN section, after a user noted that the "Dealing with defaults" section was likely in the wrong place in the steps or made an incorrect assumption about that.
- format/update notes, headings, asides
- change "instances" to apps or Machines
https://github.com/superfly/docs/issues/1383
> Private networking doc: update for Machines, clarify .internal addresses, dealing with defaults section

- about/billing.html.markerb
- about/pricing.html.markerb
Add that GPU billing is by the second (while prices are by the hour).
> Pricing and Billing: GPUs are by the second

- machines/api/machines-resource.html.markerb
- machines/flyctl/fly-machine-run.html.md
`auto_stop` -> `autostop`
`auto_start` -> `autostart`
The Machines API docs might be incorrect. When creating and updating Machines using the field names `auto_stop`, `auto_start`, these settings don't seem to take. However, using `autostop` and `autostart` works!
> Correct `auto_stop`, `auto_start` field names in Machines docs

- machines/api/working-with-machines-api.html.markerb
* don't link to the external API app at the top
* don't recommend `fly machines api-proxy` since we have a public API URL now
* you don't have to use org-wide tokens -- didn't explain all the options; for now making it clear we're using the token flyctl is using in the example
* general tidying
* still should explain somewhere about deploy tokens (better, have a doc on tokens)
> Clean up working with Machines API page

- machines/api/index.html.md
- machines/index.html.md
- machines/overview.html.markerb
- partials/_firecracker_nav.html.erb
- partials/_machines_nav.html.erb
- volumes/index.html.markerb
- [Machines landing page](https://fly.io/docs/machines/): re-write the intro, cull the links down to 3 main ones, (move the image from API landing page to here). Preview: https://aa-docs-3.fly.dev/docs/machines/
- [Machines overview](https://fly.io/docs/machines/overview/): update content, change the warning into a section on "Do I need to control Machines?" (title TBD?), suggest changing the doc name to "Introduction to Machines" for friendliness and accuracy. Preview: https://aa-docs-3.fly.dev/docs/machines/overview/
- [Machines API landing page](https://fly.io/docs/machines/): Add descriptions to links. Preview: https://aa-docs-3.fly.dev/docs/machines/api/
- updated order and so on for main nav and Machines nav
https://aa-docs-3.fly.dev/docs/machines/
> Machines docs: update landing pages, intros, links, and words

- networking/dynamic-request-routing.html.md
It wasn't clear to me which region the proxy would fall back to if the requested region has no healthy instances.
> Clients accessing Fly.io apps may set the `fly-prefer-region` header to attempt sending the request directly to a desired target region. This is useful for cases where `fly-replay` isn't practical, such as large file uploads which can't be replayed once buffered by the proxy.
>
> If the target region has no healthy instances, the region nearest to the client with healthy instances will field the request.
> Disambiguate Fly-Prefer-Region docs

- networking/custom-domains-with-fly.html.md
In my testing I came across this issue — we perform a hostname check and unless an IPv6 is associated with an app, we won't attempt to issue (or renew) a cert.
(These docs are in need of a bigger overhaul, I think)
> Hostname validation will fail without an IPv6 address

- reference/configuration.html.markerb
Adds a note to the fly.toml reference doc that if you use the `connections` concurrency type, you get a new connection per http request.
This is a minimum viable change -- the fly.toml reference is where this info will have the most impact, but isn't where the canonical info should ultimately live.
> fly.toml: Connections concurrency type opens a new conn per req

- hiring/working.html.md
Seems like `/levels` is an old page that should point to `/company-levels` instead (the main nav links to `/company-levels`).
> change link to 'company-levels' instead of 'levels'

- js/frameworks/astro.html.markerb
This PR simplifies the setup instructions for Astro apps a bit. The `npx astro add node` command automatically makes the correct changes to the `astro.config.*` file[^1], so I've removed that redundant info and replaced it with a little descriptor of what that command does.
I also noticed how this doc says to run `fly deploy` to deploy apps running `fly launch`. In my experience, `fly launch` appears to also handle the initial deployment, but I may be missing something here. Happy to make that change in this PR if y'all would like.
- [Official `@astrojs/node` docs][astro-node]
- I also opened a PR to stub out a Fly.io deployment guide in the official Astro docs: https://github.com/withastro/docs/pull/7799
Thanks for the great docs on this!
[^1]: See [their docs][astro-node] for more on …
> docs: simplify astro setup instructions

- app-guides/livebook.html.markerb
There's an issue with the display of long titles that contain very long words with code markup, but this is a very rare case, so to save time I just reworded the title. :)
> Reword title to avoid weird rendering

- rails/advanced-guides/phusion-passenger.html.md
- rails/cookbooks/deploy.html.markerb
With the rollout of [overlayfs](https://flyio.discourse.team/t/fresh-produce-a-new-way-to-rootfs/5386), trying to create a swapfile will no longer be a workable solution.
https://community.fly.io/t/a-new-way-to-rootfs/19196
> chore: replace docs on creating a swapfile with using swap_size_mb

- machines/api/machines-resource.html.markerb
Added some missing services properties for Machine config object.
> API docs: add some missing machine config properties

- reference/volumes.html.markerb
Change default volume size from 3 GB to 1 GB.
This corresponds to the work done in https://github.com/superfly/flyctl/pull/3455.
> Change default volume size from 3 GB to 1 GB

- partials/_firecracker_nav.html.erb
- reference/autoscaling.html.md
Adds reference documentation on autoscaling capabilities on our platform
I'm not sure how in depth the reference should be. Both link out to the respective features and documentation, just providing a short overview of the features. Also, the name "pre-allocated machine autoscaling" sucks but i'm not sure how else to describe it. Open to ideas!
> add ref docs on autoscaling

- networking/services.html.markerb
Remove that you need an dedicated IPv4 to use wildcard certificates, because we now support that
> Remove that you need an dedicated IPv4 to use wildcard certificates

- reference/configuration.html.markerb
Users are able to add kernel parameters to the vm. This functionality has been present but undocumented for a while.
> Add vm.kernel_args to fly.toml reference

- reference/supabase.html.md
Supabase is not ready for prime time, so we're downgrading it to 'alpha' to align with their wording and expectations.
> Clarify Supabase alpha

- about/pricing.html.markerb
- gpus/getting-started-gpus.html.md
- gpus/gpu-quickstart.html.markerb
- gpus/index.html.md
- kubernetes/using-gpus.html.markerb
- reference/configuration.html.markerb
Extend GPU documentation to include references for new Nvidia A10 cards
https://github.com/superfly/fly-go/pull/45
> Fill in details for new Nvidia A10 cards

- reference/deploy-tokens.html.md
remove the note about deploy tokens being experimental; we're clearly beyond those early days
> Remove experimental feature note

- js/frameworks/nextjs.html.markerb
Generate the Next.js app with `create-next-app`
n/a
The update is about generating a new Next.js app with `create-next-app` instead of redirecting the user to a tutorial at nextjs.org
The're are other suspects for improvement in the guide:
- I haven't noticed any improvement in the image size after applying the "standalone" config option
- ~~the `COPY` instructions suggested as an alternative make the resulting VM crash with~~
But I'll leave it for later / others since I'm just wrapping my head around the Next.js.
> Update the Next.js guide

- elixir/the-basics/clustering.html.md
- postgres/connecting/app-connection-examples.html.markerb
- postgres/managing/upgrades.html.markerb
- rails/getting-started/existing.html.md
- reference/error-codes.html.md
- reference/sentry.html.md
Fix typos in documentation
- change `dns_cluser` to `dns_cluster` 
- change `consturctor` to `constructor`
- change `Postgress` to `Postgres`
- change `accomodate` to `accommodate`
- change `occured` to `occurred`
- change `parternships` to `partnerships`
> Fix typos in documentation

- litefs/position.html.markerb
Fix link to https://fly.io/docs/litefs/events/
Otherwise https://fly.io/docs/litefs/position/ has a broken link in it.
> Fix broken link: Update position.html.markerb

- languages-and-frameworks/axum.html.markerb
change the `layout` in front matter so the Axum app doc doesn't open its own nav
> Fix layout for Axum doc nav

- js/frameworks/nextjs.html.markerb
This adds _Connecting to Supabase Postgres_ section to the Next.js guide.
It hand-holds the user through a process of connecting their Next.js project launched at Fly.io to Supabase with [`supabase-js`](https://www.npmjs.com/package/@supabase/supabase-js).
* The changes ignore the fact that Supabase is a web development platform and thus doesn't mention how it fits into the Client/Server Components, Middleware etc. (see https://supabase.com/docs/guides/getting-started/quickstarts/nextjs)
* adding that would bloat this section significantly
* Shall we add something similar but with [`Prisma`](https://www.prisma.io/nextjs)? @anniebabannie 
* Do we want to attract devs only interested in using Supabase to build their apps? Even if they host them somewhere else?
* @raethlo you may know the …
> Extend Next.js guide with Supabase Postgres

- reference/configuration.html.markerb
Added a section about what `services.machine_checks` are and how to use them.
Please see https://github.com/superfly/flyctl/pull/3430 for the corresponding flyctl PR
> Add a section about machine_checks

- blueprints/bridge-deployments-wireguard.html.md
Adds a blueprint doc for how you can bridge your existing networks to your fly.io private network.
A standard "how to wireguard on linux" tutorial with suggestions for what to do next to inspire people to take it further.
> blueprints: add wireguard bridging doc

- about/pricing.html.markerb
We've stopped giving free allowances to trial orgs to avoid potential for abuse.
> Free allowances no longer given to free trial orgs, only orgs on a paid plan.

- blueprints/multi-region-fly-replay.html.md
Add a new blueprint for Multi-region apps with read replica dbs that use the `fly-replay` request header.
> Blueprint: multi-region dbs and fly-replay

- volumes/overview.html.markerb
The reminder about volumes not replicating themselves got removed in a previous edit. This PR adds it back.
Also adding links to LiteFS and Supabase.
> Volumes: add replication back into the warning

- getting-started/essentials.html.md
- getting-started/index.html.md
- partials/_firecracker_nav.html.erb
Add a new doc that is a primer on some Fly.io basics like what are Machines and what is Fly Launch?
Add a glossary of Fly.io terms. We can add to this (6PN, Flycast, etc.)
https://aa-docs-3.fly.dev/docs/getting-started/essentials/
> Getting started: add Fly.io Essentials doc

- networking/private-networking.html.md
- fixed a typo (by removing the sentence!)
- re-arranged the Flycast intro to say what Flycast is first
- added a note in the 6PN address section about Flycast
- tbh, there were way too many semicolons in the intro to the page
> Private networking: typo and edits

- machines/guides-examples/machine-restart-policy.html.markerb
- reference/configuration.html.markerb
The ability to specify a restart policy in the Fly.toml was added a couple months ago, but never made it into docs. This adds details to the fly.toml reference, and the restart policy doc. 
https://community.fly.io/t/more-control-over-your-app-restarts/19180 announcement post
> Add Restart Policy section to Fly.toml docs

- blueprints/autostart-internal-apps.html.md
New blueprint to explain how you can use a Flycast address for an internal app to get Fly Proxy features like autostart/autostop.
> Blueprint: Autostart/autostop internal apps

- elixir/getting-started/index.html.markerb
- js/frameworks/partials/_flyctl.html.erb
- js/frameworks/partials/_intro.html.erb
- languages-and-frameworks/partials/_flyctl.html.erb
- languages-and-frameworks/partials/_intro.html.erb
- change "your Fly app command center" to "the Fly.io CLI"
- change "Fly.io global application platform" to "Fly.io platform"
> Update Fly.io terms in partials

- about/pricing.html.markerb
- styles/config/vocabularies/fly-terms/accept.txt
This PR clarifies pricing for data transfer by adding more detail to what 'outbound' means, and clarifying which services offer free VM->service bandwidth (currently, Tigris).
Also, we clarify that provisioning extensions will not lead to extra charges for the managed service machine.
> Clarify pricing for data transfer and extensions

- about/pricing.html.markerb
Links to tigris, supabase and upstash references were broken in the pricing page.
> Fix link to extension references in the pricing page

- reference/supabase.html.md
This puts less scary wording around the alpha, which Supabase is more confident about supporting now.
> Clear up Supabase alpha release status

- languages-and-frameworks/index.html.erb
- networking/index.html.markerb
- add a link to python docs from frameworks index page
- fix an unrelated typo elsewhere
> Add python link

- apps/autoscale-by-metric.html.markerb
- partials/_firecracker_nav.html.erb
- reference/autoscaling.html.md
Add docs for fly-autoscaler, the metrics-based autoscaler app.
> Add docs for fly-autoscaler

- getting-started/get-started-by-framework.html.markerb
- getting-started/index.html.md
- getting-started/launch-demo.html.markerb
- getting-started/launch.html.markerb
- languages-and-frameworks/partials/_scanner_guides.html.erb
- partials/_firecracker_nav.html.erb
- reference/autoscaling.html.md
- move the full list of languages and frameworks from the Quickstart to a new page "Get started with your language or framework"
- add a "Choose a language or framework" entry in the Getting started nav that links to the new page
- keep the Languages and Frameworks top-level entry in the nav, but change the sub-levels from "Run a Foo app" to just "Foo" and have them link to the main framework section page rather than getting started. Add an entry for "More...".
- having the list of languages and frameworks in the quickstart didn't make sense anymore, since users would have already run `fly launch` before reading the list
> Getting started changes for languages and frameworks

- getting-started/launch.html.markerb
> Add a link to frameworks from quickstart

- kubernetes/fks-quickstart.html.markerb
Document some caveats that I discovered while smoke-testing FKS for a content prototype.
https://github.com/superfly/flyio-virtual-kubelet/issues/104
> kubernetes/fks-quickstart: document logs being per namespace and kubectl run not working

- blueprints/staging-prod-isolation.html.md
Add a doc that explains when you'd want to use organizations to isolate staging and production environments.
https://aa-docs.fly.dev/docs/blueprints/staging-prod-isolation/
> Blueprint: Staging and production isolation

- about/healthcare.html.markerb
- about/index.html.markerb
- updated the About index page with accurate content list and company naming
- added a link from healthcare doc to healthcare blueprint
> Update about index and healthcare app links

- languages-and-frameworks/dockerfile.html.markerb
- updated this doc to be a bit easier to read and parse (simpler language, heading changes)
- added links at the bottom for grow and scale similar to what's at the bottom of the quickstart and launch a demo
- changed the links to volumes and postgres to link directly to the databases and storage landing page instead
> Update Dockerfile launch doc

- about/pricing.html.markerb
- the paid hobby plan is deprecated
- no new users can sign up for any Hobby plans
- if you change from the hobby plan, you can't go back
- the bit about no free allowances during the free trial was already there, but moved it to the top of the free allowances section
> Discontinued Hobby plans clarification

- getting-started/essentials.html.md
- security/sso.html.markerb
- update the definition of org in glossary
- add definition of org to SSO doc 
- add link from SSO doc to prod and staging isolation blueprint
> SSO: add what an org is and link to blueprint

- blueprints/autoscale-machines.html.md
links are at the bottom, but since autoscaler is pretty new, adding links inline to the top of the doc too
> Add links inline

- partials/_firecracker_nav.html.erb
- security/deploy-tokens.html.md
- security/index.html.markerb
move the existing deploy tokens file from reference to security
> Move Deploy tokens under security

- about/pricing.html.markerb
The region select currently just has region codes, e.g. `iad`, `eze`, etc.
This adds the city/country to the option, e.g. `Ashburn, Virginia (US) (iad)`.
> Add city and country names to region selection dropdown.

- getting-started/launch-demo.html.markerb
Show users how to delete the demo app after they create it since they don't need the app or its two Machines.
> Getting started: show how to delete the demo app

- blueprints/autostart-internal-apps.html.md
> Fix links in autostart-internal-apps blueprint

- reference/enveloop.html.md
* Added a section and links to open-source docs for Enveloop-supported frameworks and languages. 
* In pricing area, added mention that Enveloop is free to use during the beta period.
> Add ref to language and frameworks support

- languages-and-frameworks/golang.html.markerb
Add a section in the Go docs page that includes quick steps on creating and connecting with a Tigiris Bucket
> Include a Tigris section for the go docs page

- reference/regions.html.markerb
One option for adding edge-only regions to the regions table. The other option is to have them listed separately as a section below the region table.
https://aa-docs-2.fly.dev/docs/reference/regions/
> Regions: add edges

- security/sso.html.markerb
Fix typo on `Set up SSO using GitHub organization access` block.
From:
To:
> Fix GitHub SSO typo

- elixir/the-basics/clustering.html.md
- Clarify that RELEASE_COOKIE can be not only in `.toml` file, but also in secrets
- Improve transition to `Troubleshooting` section
- https://fly.io/docs/elixir/the-basics/clustering/
The original version was confusing in two aspects:
- It mentioned that cookie should be set in `.toml` file without mentioning alternatives.
- It implied going to the next step (`...we are ready for the next step!`) while next step was `Troubleshooting` which is optional.
- Code generating cookie value was after the explanation how to set it.
> Expand Elixir clustering nodes page

- apps/move-app-org.html.markerb
Mistakenly included a note that said you could use 'fly pg import" to import data across orgs. That's currently incorrect!
> Remove bit about using pg import across orgs

- python/frameworks/fastapi.html.markerb
Fix MD formatting. Not sure if single or triple backticks are appropriate here. Please adjust to whatever looks best.
> Fix MD formatting typon in  fastapi.html.markerb

- about/pricing.html.markerb
Docs for [machine reservations](https://community.fly.io/t/reservation-blocks-40-discount-on-machines-when-youre-ready-to-commit/20858).
https://community.fly.io/t/reservation-blocks-40-discount-on-machines-when-youre-ready-to-commit/20858
N/A
> Machine reservations docs

- about/index.html.markerb
- apps/index.html.markerb
- getting-started/get-started-by-framework.html.markerb
- index.html.md
- kubernetes/clusters.html.markerb
- kubernetes/connect-clusters.html.markerb
- kubernetes/fks-features.html.markerb
- kubernetes/fks-quickstart.html.markerb
- kubernetes/index.html.markerb
- kubernetes/services.html.markerb
- kubernetes/using-gpus.html.markerb
- kubernetes/using-volumes.html.markerb
- languages-and-frameworks/partials/_scanner_guides.html.erb
- machines/index.html.md
- networking/index.html.markerb
- partials/_firecracker_nav.html.erb
- reference/index.html.md
- security/index.html.markerb
- security/openid-connect.html.markerb
- volumes/index.html.markerb
- Get started by language/framework - simplify the intro and add the missing python-based scanners to the list
- give Kubernetes an index page and adjust related topic links
- move OIDC tokens into Security section
- format index pages to be more consistent (one of two "styles")
> Add index for FKS + make other index pages consistent

- partials/docs/_flyctl_install.html.erb
Updated the first sentence of the install flyctl doc to include "flyctl is a command-line utility that lets you work with Fly.io using `fly` commands..."
fixes #559
> flyctl install: "work with Fly.io using fly commands"

- monitoring/metrics.html.md
- styles/config/vocabularies/fly-terms/accept.txt
* Explain how to create a non-bearer macaroon token with restrictions (per org, read-only)
* Explain how to pass a macaroon token in the Authorization header
This process is known internally and we share it with customers who require it but a customer pointed out it's not documented which makes it difficult to discover.
> Add section on different ways to authenticate to the Prometheus API

- elixir/advanced-guides/sqlite3.html.md
Volumes are mounted under `/mnt/volume_name`.
Add explicit `volume_path` to the sample upload command to make it clearer.
> Add volume path when copying existing database

- networking/request-headers.html.md
- update the description of `Fly-Client-IP` to clarify what happens when you use a proxy, and to link to to the `X-Forwarded-For` description
- update the description of `X-Forwarded-For` for clarify why you want to go read the MDN docs
- fixes #1554 
- https://community.fly.io/t/minor-doc-correction/20944
> Request headers: update to correct inaccurate info about client IP

- machines/api/machines-resource.html.markerb
- machines/machine-states.html.markerb
- reference/configuration.html.markerb
- reference/machines/_machines_suspend_req.erb
Update documentation to account for the new Machine suspension feature, including proxy autosuspend:
* Reference the new `suspending` and `suspended` Machine states
* Document the `suspend` Machines API endpoint
* Explain how the `start` and `stop` Machines API endpoints affect `suspended` Machines
* Document new autostop settings in the Machines API and in `fly.toml`
* https://community.fly.io/t/new-feature-in-preview-suspend-resume-for-machines/20672
Still a work in progress right now!
> Updates for Machine suspension

- blueprints/review-apps-guide.html.md
I recently tried to follow this and ran into a few stumbling blocks. 
1. ~~The `steps` property is missing, so the YAML wasn't valid~~ Looks like this was fixed in another PR
2. `superfly/fly-pr-review-apps` was updated, the current version used (`1.2.0`) uses a flag that no longer exists in the flyctl, and thus this errors
https://github.com/superfly/fly-pr-review-apps/pull/56
There's also a link to a gist on Line 21, which should be updated to the latest version of `superfly/fly-pr-review-apps` as well
> Fix example YAML for GitHub Review Apps by bumping `superfly/fly-pr-review-apps` version to latest

- machines/api/apps-resource.html.markerb
- machines/api/machines-resource.html.markerb
- machines/api/volumes-resource.html.markerb
The list of endpoints at the top of the page links to relevant section now. 🎉  This always bugged me.
> API docs: make the lists of endpoints into links

- launch/autostart-stop.html.markerb
- update all the settings and wording for the new options for `auto_stop_machines`. 
- other minor fixes (more to come in a future PR)
> Update autostop/autostart for suspend Machines

- security/sso.html.markerb
For installing the Fly.io GitHub App, we link to https://github.com/apps/fly-io/installations/select_target. We actually need to set a `state` query parameter on this request. We have an endpoint at https://fly.io/app/auth/github_app that adds the parameter and redirects to the GitHub URL.
> Bad link in SSO docs

- rails/getting-started/index.html.md
It said "respond with "Y" or press enter" to the question of "do you want to make change) but the default is "N" and it says changes aren't needed, so clearly the intent was "respond with "Y""
> Fix typo on rails getting-started

- languages-and-frameworks/dockerfile.html.markerb
Fix broken link on the [Deploy with a Dockerfile](https://fly.io/docs/languages-and-frameworks/dockerfile/) page.
> Fix broken link

- blueprints/review-apps-guide.html.md
- django/advanced-guides/staging-environments-with-github-actions.html.md
- flyctl/cmd/fly_auth_token.md
- laravel/advanced-guides/github-actions.html.md
- machines/api/working-with-machines-api.html.markerb
- monitoring/exporting-logs.html.md
- rails/advanced-guides/machine.html.md
This is mostly a conversation starter. We need to move away from telling users to configure things with the output from `fly auth token`. For most users, this output is flyctl's own token, which is invalidated if the user logs out of flyctl and almost certainly has access to more things than necessary. For members of organizations that require SSO, the output from `fly auth token` is a bundle of short-lived tokens (one for each org) that can only be used by flyctl, who knows how to refresh the tokens so they keep working. Eventually, `fly auth token` will return this kind of token bundle for all users, making it inappropriate for use other than by flyctl itself.
We need to move towards recommending `fly tokens create <token-type>`:
- `fly tokens create deploy [-a app-name]` - Token for …
> Start replacing `fly auth token` with more limited tokens

- machines/api/working-with-machines-api.html.markerb
Quote shell variable
N/A
https://fly.io/docs/machines/api/working-with-machines-api/
The previous command results in an error.
```
% fly secrets set FLY_API_TOKEN=$(fly tokens deploy)
Error: Validation failed: Name only allows letters, numbers, and underscores
```
> Fix issue working-with-machines-api.html.markerb

- apps/app-availability.html.markerb
Testing shows that the behaviour whereby we delete the standby first when scaling with `fly scale count` doesn't apply anymore. Updating docs to show how to identify and delete the standby.
> Update how to remove a standby Machine

- security/tokens.html.markerb
> Fix numbering in tokens doc

- reference/configuration.html.markerb
Add idle-timeout http_options configuration to docs
https://github.com/superfly/flyctl/pull/3827/
> Add idle_timeout http settings

- machines/api/volumes-resource.html.markerb
Volumes update curl example `POST` → `PUT`
https://community.fly.io/t/retain-your-snapshots-from-1-to-60-days-your-choice/19651/5
> Fix volumes update method

- blueprints/autoscale-machines.html.md
- blueprints/autostart-internal-apps.html.md
- blueprints/resilient-apps-multiple-machines.html.md
- launch/autostop-autostart.html.markerb
- reference/fly-proxy-autostop-autostart.html.markerb
- Edits/updates  in various files re autostop/autostart
- fixes #1775
> Edits for autostop/autostart

- networking/dynamic-request-routing.html.md
- networking/index.html.markerb
- security/index.html.markerb
that. and a few other minor fixes to dynamic request routing doc
> Add custom networks to index

- about/billing.html.markerb
> Clarify that suspended machines are billed the same as stopped

- reference/regions.html.markerb
There are 38 regions in total, but users can only deploy to 35.
> Change number of regions

- reference/configuration.html.markerb
The machine_checks toml example showed `/bin/sh -c` being given multiple arguments. But /bin/sh -c should be given a single argument that's a long single string containing the bash to execute.
> Fix machine_checks example error

- launch/continuous-deployment-with-github-actions.html.md
- monitoring/sentry.html.md
- partials/_apps_nav.html.erb
- partials/_firecracker_nav.html.erb
- security/arcjet.html.md
- supabase/index.html.md
- tigris/index.html.markerb
- upstash/kafka.html.md
- upstash/redis.html.md
- upstash/vector.html.md
- create directories for Upstash, Supabase, and Tigris
- move some files into the right directories, like Arcjet and Sentry
- add redirects
> Create new directories (for the breadcrumbs!)

- about/extensions.html.markerb
- about/pricing.html.markerb
- apps/going-to-production.html.markerb
- apps/move-app-org.html.markerb
- blueprints/cell-based.html.md
- database-storage-guides.html.md
- happy-path/aim.html.markerb
- happy-path/postgresql.html.markerb
- happy-path/redis.html.markerb
- happy-path/tigris.html.markerb
- index.html.md
- js/frameworks/nextjs.html.markerb
- js/the-basics/object-storage.html.md
- laravel/database-guides/laravel-redis.html.markerb
- monitoring/index.html.markerb
- monitoring/search-logs.html.markerb
- postgres/getting-started/what-you-should-know.html.md
- rails/cookbooks/databases.html.markerb
- rails/getting-started/index.html.md
- rails/the-basics/active-storage.html.md
- rails/the-basics/sidekiq.html.md
- rails/the-basics/turbo-streams-and-action-cable.html.md
- reference/configuration.html.markerb
- security/index.html.markerb
- volumes/overview.html.markerb
> Fix related topic redirects that broke build

- apps/trouble-host-unavailable.html.markerb
- postgres/managing/backup-and-restore.html.markerb
There's some interop issues with restoring a snapshot for an older stolon PG into a new postgres-flex cluster. It's also not ideal to restore across different major versions of pg-flex. This updates the PG restore docs to add a section on  how to find your image and specify it when restoring the pg cluster. It also updates the PG restore instructions in the single host failure doc.
Resolves https://github.com/superfly/docs/issues/1772
> Update PG Snapshot restore instructions

- apps/going-to-production.html.markerb
Implements the new checklist card thingy in our Going to Production doc.
> Checklist card component

- apps/going-to-production.html.markerb
- monitoring/metrics.html.md
- check pg backups
- metrics
- edits
> Prod checklist: updates from feedback

- apps/going-to-production.html.markerb
- apps/index.html.markerb
- blueprints/autostart-internal-apps.html.md
- getting-started/index.html.md
- getting-started/troubleshooting.html.md
- index.html.md
- launch/continuous-deployment-with-github-actions.html.md
- launch/volume-storage.html.markerb
- partials/_apps_nav.html.erb
- partials/_firecracker_nav.html.erb
- reference/configuration.html.markerb
- reference/fly-launch.html.md
- reference/index.html.md
- add checklist link to main page
- add more networking links to main page
- merge Machines and Machines API sections on main page
- updates to checklist intro
- update app config links from various pages
> Updates to main page and related things

- about/billing.html.markerb
- about/pricing.html.markerb
- blueprints/staging-prod-isolation.html.md
- getting-started/essentials.html.md
- security/sso.html.markerb
- minor changes to various docs to update the definition of an "org" so it doesn't say "separate billing" and or links to unified billing docs
> Minor updates for unified billing

- happy-path/index.html.markerb
- happy-path/launch-deep-dive.html.markerb
---
The front page had a number of (in my opinion) disjoint sentences that could leave the wrong impression.
One way to interpret the way it was:
- It normally will take a minimum of an afternoon, expect surprises, but we will partner with you.
I reworded it with the intent to convey:
- It normally will take a minimum of an afternoon, we will complete it in minutes.
- We have taken steps to minimize surprises, but if you encounter one we will partner with you.
I also added a link to public networking, and mentioned preconfigured databases.
---
I added Django in (it should be complete by the time this page goes live).  I removed repetitive sentences and replaced them with a simple link.
> Deep Dive updates:

- reference/configuration.html.markerb
See: https://community.fly.io/t/volume-not-automatically-extending/21551
> Document that auto_extend_size_limit is required if you want your volume to extend

- about/billing.html.markerb
Converting an existing organization to a Linked Organization.
@andie787 I'm going to merge this one and we can follow up with any necessary tweaks.
> converting an existing organization to a linked org

- languages-and-frameworks/static.html.markerb
* Static site example has nginx now, updates docs to reflect
* Updates show updated output from Fly commands
https://github.com/fly-apps/hello-static/pull/4
I'm looking to give folks a way to create an empty app in dashboard - those users will need slightly different instruction for a first deploy. This is one thread they can follow to get something shipped. I noticed some things were getting dusty with this example so I've updated it and used nginx which has better defaults than an abandoned go library.
> update static site docs with http_service, new nginx example

- about/pricing.html.markerb
- machines/overview.html.markerb
> Add documentation and pricing for static machine IPs

- flyctl/cmd/fly_volumes_snapshots.md
Removes confusing wording, as volume snapshots can't be used to restore a volume to a previous state, only to create new ones.
> Update volume snapshot restore definitions.

- apps/move-app-org.html.markerb
Tigris reached out and said that they don't support moving buckets between orgs, and asked if we could remove this line from the docs.
Slack thread: https://flyio.slack.com/archives/C053VNRRERW/p1730157072437689
> Remove incorrect mention of Tigris

- networking/dynamic-request-routing.html.markerb
clarifies that fly-replay won't work for services without the http handler.
> added http handler to limitations section

- reference/configuration.html.markerb
* https://github.com/superfly/flyctl/pull/4085
> reference docs for [deploy.release_command_vm]

- about/index.html.markerb
- apps/going-to-production.html.markerb
- apps/index.html.markerb
- getting-started/launch.html.markerb
- gpus/index.html.md
- monitoring/index.html.markerb
- security/index.html.markerb
Add illustrations on multiple pages
> Illustrations update

- reference/configuration.html.markerb
Much like the `[[http_service.checks]]` section, the `[[http_service.machine_checks]]` needs to be in double parenthesis.
> Fix `http_service.machine_checks` code example

- languages-and-frameworks/golang.html.markerb
fixes https://github.com/superfly/docs/issues/1869
The golang Dockerfile template was updated in https://github.com/superfly/flyctl/pull/3312 to use Debian instead of Alpine -- this change brings the relevant docs up to date.
just a quick attempt to make the docs correct -- i imagine you'll want to reword in a brand-consistent voice and maybe rethink the section anyway in light of the new default.
> Update golang Dockerfile docs to match template changes

- postgres/getting-started/enabling-timescale.html.markerb
The guide didn't work if followed in order as the user doesn't know the database name until it's attached to an app. Instead, we connect to the database server without a database specified to create the extension, then attached to an app to create a database.
Also updated to timescale 16
> Fix issue with Tiemscale DB setup guide

- postgres/connecting/connecting-external.html.markerb
In a nutshell: Change of `flyio/postgres` to `flyio/postgres-flex`
https://community.fly.io/t/failed-to-fetch-an-image-or-build-from-source-could-not-find-image-docker-io-flyio-postgres-xx-x/19602
`flyio/postgres` is no longer a valid image, instead we should use `flyio/postgres-flex` and the docs should reflect that.
> Change `flyio/postgres` to `flyio/postgres-flex`

- apps/overview.html.markerb
Fixed the link and made the clickable portion consistent with earlier points in the docs.
> Fix broken link in Overview docs

- security/arcjet.html.md
Updated from using a direct discord.gg link to one that we own.
> fix: use new arcjet discord link

- reference/configuration.html.markerb
A user reported an error when trying to use the `canary` deployment strategy on a Machine with an attached volume. This limitation was confirmed for both canary and bluegreen strategies. Updating the docs to clarify and reflect this limitation.
> update attached volume limitation on canary and bluegreen strategies

- about/support.html.md
- litefs/index.html.markerb
- monitoring/index.html.markerb
- postgres/index.html.md
Added a scope of support portion to the about/support page in the docs. Created a grid and also added the important bubbles to products that aren't supported/limited-support.
> Scope of support

- launch/autostop-autostart.html.markerb
Added a warning description under min_machines_running for users, to make sure it is clear that the setting only maintains the specified minimum number of running machines in the app's primary region
> Add a warning message to min_machines_running

- index.html.md
Add link to flyctl installation details on the homepage
> Homepage link to flyctl installation details

- machines/cpu-performance.html.md
- monitoring/metrics.html.md
Editing pass on the CPU Performance docs, adjusting some of the terminology, adding some more specific references. Also added some additional details to the metrics page on the newly-added `fly_instance_cpu_` metrics.
> edits to CPU Performance docs

- monitoring/metrics.html.md
Fixes #1964 
The [querying section](https://fly.io/docs/monitoring/metrics/#querying:~:text=number%20of%20series.-,Querying,-Queries%20can%20be) mistakenly refers to the authorization header as using “Bearer” instead of the correct “FlyV1”. Where the API actually expects the header to be “Authorization: FlyV1 <token>”.
> Fix authorization header in metrics docs (fixes #1964)

- mpg/overview.html.md
Updated image path on "Managed postgres overview doc"
> fix: update image paths in Managed Postgres overview

- js/shopify.html.markerb
- styles/words2ignore.txt
- Adding a note for folks deploying Shopify apps through the launch UI
https://app.plain.com/workspace/w_01J30S94JDD57QXMT9Q47J928E/thread/th_01JPTC5RKK8STREXXAPFQN7JSD/
> Update Shopify docs for PaaS users

- deep-dive/tigris.html.markerb
Added image to tigris.html.markerb
> Added tigris image to tigris.html.markerb

- partials/_firecracker_nav.html.erb
- reference/health-checks.html.markerb
- reference/index.html.md
Added a brand new doc - health checks to the reference section of the docs. It encompasses all there is to know about health checks and the different types.
> Completed health checks doc

- reference/configuration.html.markerb
Added a callout for the vm section in a fly.toml affecting machine sizing on deploys. This should hopefully make it clear so that customers understand the reason why scaling might change after deploying if a vm section is present
> Add callout for vm section affecting deployments for machine sizes

- about/pricing.html.markerb
- launch/autoscale-by-metric.html.markerb
- Removed line about data transfer to Tigris being free.
- Removed references to the `-o` flag for the `fly tokens create` command, which is not a valid flag.
- [Community forum post](https://community.fly.io/t/tigris-billing-for-inbound-data-from-fly-tigris/24164) about Tigris data transfer
- [Internal Discourse discussion](https://flyio.discourse.team/t/customer-getting-billed-for-data-transfer-into-tigris/8107) about Tigris data transfer pricing
- [HS ticket](https://secure.helpscout.net/conversation/2865475001/124530?viewId=6664451) for the `-o` flag
> Remove reference to Tigris data transfer being free

- machines/guides-examples/one-app-per-user-why.html.markerb
Just what it says on the tin ☝🏻
> fix: remove colon from title to appease build

- blueprints/per-user-dev-environments.html.md
- networking/dynamic-request-routing.html.markerb
Add docs for `fly-replay-cache`, a [new proxy feature](https://github.com/superfly/fly-proxy/pull/1544)
> Add docs for fly-replay-cache

- machines/guides-examples/one-app-per-user-why.html.markerb
- partials/_firecracker_nav.html.erb
- partials/_machines_nav.html.erb
- Added a link to the new "one app per customer" to both the main side navbar and the Fly Machines detail page side navbar
- Updated the title casing to match the conventions for the other pages
Main side navbar | Fly Machines side navbar
-----|-----
> Update nav to add links for the "one app per customer" doc

- reference/configuration.html.markerb
Added a callout to clarify that both auto_extend_size_increment and auto_extend_size_limit must be set for the volume auto-extension feature to work. Removed individual “Required with...” lines to reduce redundancy and improve clarity.
> clarify required settings for volume auto-extension

- machines/api/machines-resource.html.markerb
Some of the field names here were inconsistent and referred to those in the fly.toml but the field names in a machine's configs are slightly different.
A machine config has:
"extend_threshold_percent": 80, 
"add_size_gb": 1,
"size_gb_limit": 10
> Ensure resizing parameter names refer to machine config fields and not fly.toml option names.

- machines/api/machines-resource.html.markerb
Clarified the mounts section in the Machines API docs to explain that volumes are tied to physical hosts, and a Machine can only mount a volume on the same host.
> Clarify volume mount behavior in Machines API docs

- reference/fly-proxy-autostop-autostart.html.markerb
Added a new section explaining how Fly Proxy behaves when neither `auto_start_machines` nor `auto_stop_machines` is set in the `fly.toml` file.
> clarify Fly Proxy behavior when autostart/autostop are not set

- reference/fly-proxy-autostop-autostart.html.markerb
Fix small typo in docs for autostop/autostart not set, for the last [PR](https://github.com/superfly/docs/pull/2034) put up.
> Fix small typo in docs for autostop/autostart not set

- blueprints/base-images-for-faster-deployments.md
This documentation covers how to create base images in a way that lists the registry URL in `fly releases` and the registry tab.
https://gist.github.com/symkat/399eddeec2dcc659209aaafcbecf3d4a
> Create doc: blueprints/base-images-for-faster-deployments

- partials/_firecracker_nav.html.erb
- Updated the top-level nav to go directly to the doc page that makes the most sense, rather than an intermediate "overview" page. (Ironically, a lot of those more-relevant pages are referred to as "overviews" in the code.)
NOTE: I left some of the top-level links as-is where it made sense, like for the Blueprints link.
> Make top-level doc links navigate directly to relevant pages

- machines/guides-examples/network-policies.html.markerb
- partials/_machines_nav.html.erb
Adds a new guide under Machines that explains how to use network policies to control ingress and egress traffic. Includes usage examples, selector and rule structure, API endpoints, and troubleshooting tips.
> Add guide for using network policies with Fly Machines

- blueprints/using-base-images-for-faster-deployments.html.md
Adds a related use case that links to the https://fly.io/docs/blueprints/using-the-fly-docker-registry/ docs.
https://gist.github.com/symkat/399eddeec2dcc659209aaafcbecf3d4a#related-use-case
> Add related use case for docker registry

- partials/_firecracker_nav.html.erb
- reference/aws-to-fly-guide.html.md
- reference/index.html.md
Adding new doc: AWS to Fly.io overview guide
I've placed in the Reference section, but I'm open to other suggestions!
Illustration to be added soon via follow up PR
> add AWS to Fly overview guide

- machines/guides-examples/multi-container-machines.html.markerb
- partials/_machines_nav.html.erb
This guide explains how to run multiple containers on a single Fly Machine using the containers array and Pilot, with practical examples including:
sidecar patterns (metrics/logs, secrets agents, load smoothing, storage layers)
container dependencies (depends_on)
container health checks
deploying multi-container Machines via:
Machines API
flyctl machine run
fly deploy (as of flyctl v0.3.113)
The goal is to give customers a clear, accurate starting point for running sidecars and related patterns on Fly Machines.
> (WIP)Add multi-container machines doc

- litefs/index.html.markerb
fixed some broken links on https://fly.io/docs/litefs/
broken links:
none
none
> fix links in index.html.markerb

- networking/dynamic-request-routing.html.markerb
Updating the replay documentation to note that `fly-replay-cache` no longer requires the domain to be included.
> Update replay cache docs for fly-replay-cache without domain

- apps/going-to-production.html.markerb
prepend /docs to the link under High Availability & Global Replication
> Add /docs path to High Availability & Global Replication link

- app-guides/mysql-on-fly.html.markerb
as reported also elsewhere (e.g. https://community.fly.io/t/error-deploying-mysql-database/20008/4 ) the mysql:8 image suggested in the example fails to work in the end (mysqld keeps erroring out due to missing mysql.component and unknown default auth plugin).
This is quickly fixed by using at least v 8.0.37. 
Haven't checked other versions, this is good enough for anyone taking this for a quick spin
> Update mysql-on-fly.html.markerb to use at least mysql:8.0.37

- machines/guides-examples/multi-container-machines.html.markerb
The following items are taken from this [Discourse post](https://flyio.discourse.team/t/docs-for-multi-container-pilot-machines-has-problems/8754)
See this [comment](https://github.com/superfly/docs/pull/2103#discussion_r2178445854)
> Fixes for multi-container machines guide

- apps/app-handover-guide.html.md
- partials/_apps_nav.html.erb
Based on a section from the Sol Arch guide
This will live in the Apps section of the docs
> add new doc: app handover guide

- apps/app-availability.html.markerb
- blueprints/staging-prod-isolation.html.md
- getting-started/essentials.html.md
- getting-started/troubleshooting.html.md
- launch/create.html.markerb
- reference/health-checks.html.markerb
- reference/machine-migration.html.markerb
Add new images:
- https://fly.io/docs/getting-started/essentials/
- https://fly.io/docs/launch/create/
- https://fly.io/docs/blueprints/staging-prod-isolation/
- https://fly.io/docs/apps/app-availability/ AND https://fly.io/docs/reference/machine-migration/ (same image as AWS to Fly guide)
-  https://fly.io/docs/reference/health-checks/
Swap:
- https://fly.io/docs/getting-started/troubleshooting/ (change existing image)
Previewed locally
Tracking issue: https://github.com/superfly/docs-tracking/issues/36
PR to add images to landing repo: https://github.com/superfly/landing/pull/1012
> Add illustrations to various docs

- flyctl/cmd/fly_scale_vm.md
Wraps --vm-memory in backticks so the double dashes render correctly instead of being converted by markdown. Makes it more readable with clearer phrasing and formatting as well
> Clarify fly scale vm flag/wording

- partials/_firecracker_nav.html.erb
Removed the "Docs Index" backlink on pages that don't have a different side nav.
> Removed docs index link on pages that have the same main side nav

- blueprints/task-scheduling.html.md
- New guide for task scheduling on Fly.io
- Based on topic from Solutions Arch guide
> Add new doc: task scheduling guide

- partials/_litefs_nav.html.erb
- partials/docs/_litefs_sunset.html.erb
Removed litefs cloud from the nav, but kept the pages for SEO purposes. Changed the wording in the sunset callout about litefs cloud being deprecated
> Remove litefs cloud from nav and change wording of it being deprecated

- about/billing.html.markerb
- about/pricing.html.markerb
Our billing and pricing docs are unclear about free allowances, free trial credits and labeling of Legacy plans
This PR will clarify that information
Relevant docs: 
https://fly.io/docs/about/pricing/
https://fly.io/docs/about/billing/
> Free allowances / trial credit / legacy plans clarifications

- mpg/extensions.html.md
Reorganized the documentation to provide an overview and usage instructions for the new Extensions page, clarified the process for enabling third-party extensions (currently vector and postgis), and replaced the default extensions list with a table indicating which extensions can be enabled.
> Revise MPG extensions documentation

- about/support.html.md
The page is long, first of more improvements to come is: 
- adding a TOC to the page
- changing the headings to group paid support items
- adding a section and link to the main support page so users can compare and select a plan
Previewed in local env
> initial improvements to support docs page

- partials/_firecracker_nav.html.erb
- reference/index.html.md
- reference/suspend-resume.html.md
- Add new doc to Reference section covering Machine Suspend and Resume (how it works, usage, requirements, limitations, etc.)
This topic came up in Solutions Architecture sessions and was also requested by the Support Team
Previewed in local env
> Add new reference doc: Machine suspend-resume

- mpg/configuration.md
- mpg/create-and-connect.html.md
- partials/_firecracker_nav.html.erb
- Creates a new "Configure your cluster" docs page for MPG. 
- Moves the "PG Bouncer Config" section from Create & Connect
- Adds plan configuration info
- Adds user / role configuration information.
> Add MPG configuration doc

- blueprints/task-scheduling.html.md
- Task scheduling guide wasn't appearing in docs site search results for the term "cron"
- Making a few updates to improve the search results: (adding cron to the title, adding cron to opening paragraph, adding cron as a category keyword)
> Task scheduling guide search improvements

- getting-started/essentials.html.md
- fix two links that point to redirected pages
- add two links (organizations, scale by metrics)
> Add and revise links in Fly Essentials

- apps/secrets.html.markerb
Improving Secrets docs
- add new section: mounting secrets on the filesystem
- add headings and subheadings for easier navigation
requested by @lillianberryfly
> Add mounting secrets section and headings to Secrets doc

- monitoring/metrics.html.md
Clarified which tokens use Bearer vs FlyV1 in the metrics docs.
> Add tokens clarification for authorization headers

- blueprints/deno-kv-litefs.html.markerb
- This blueprint has deprecated content (LiteFS Cloud), so removing it from the blueprints side nav and index page, but keeping the page for seo purposes for now
- `published: false` in frontmatter removes from nav and index, while keeping the page still reachable via url.
- There's already a deprecation notice on the page
- verified change in local env
> Remove litefs cloud blueprint from side navigation and Blueprints index

- mpg/index.html.md
MPG now supported across the following regions - 
```
- `ams` - Amsterdam, Netherlands
- `fra` - Frankfurt, Germany
- `gru` - São Paulo, Brazil
- `iad` - Ashburn, Virginia, USA
- `lax` - Los Angeles, California, USA
- `nrt` - Tokyo, Japan
- `ord` - Chicago, Illinois, USA
- `sin` - Singapore
- `sjc` - San Jose, California, USA
- `syd` - Sydney, Australia
```
> mpg regions no longer "coming soon"

- reference/configuration.html.markerb
- Update the `kill_signal` and `kill_timeout` runtime options config reference with info on shutdown sequence behavior
- Copy edit to the rest of the sub-sections for clarity
- Inspired by info from the Solutions architecture guide
> Update runtime options config reference with shutdown sequence behavior

- reference/autoscaling.html.md
Adding new illustration to [Autoscaling Reference page](https://fly.io/docs/reference/autoscaling/)
> Add new autoscaling illustration to reference page

- reference/health-checks.html.markerb
(expanded from Sol Arch guide)
- health check options for apps with no services (like job runners and queue workers)
checked in local env
> Add health checks info for apps with no services

- machines/api/machines-resource.html.markerb
> link persist_rootfs option in machine object config to app reference docs

- mpg/index.html.md
Says "Databases created or deleted mid-month will have their pricing prorated accordingly.", should say "Clusters created or deleted mid-month will have their pricing prorated accordingly."
https://community.fly.io/t/pricing-clarification-for-mpg/26066/2
> Correct confusing reference to database pricing - should be cluster

- reference/configuration.html.markerb
- volumes/snapshots.html.markerb
Document new `[mounts]` `scheduled_snapshots` option.
* https://github.com/superfly/flyctl/pull/4586
* Related: https://github.com/superfly/docs/pull/2246
> Document scheduled_snapshots in fly.toml

- blueprints/multi-region-fly-replay.html.md
- blueprints/per-user-dev-environments.html.md
- blueprints/remote-mcp-servers.html.md
- blueprints/resilient-apps-multiple-machines.html.md
- blueprints/review-apps-guide.html.md
- blueprints/sticky-sessions.html.md
- blueprints/using-base-images-for-faster-deployments.html.md
Add illustrations links to these guides:
https://fly.io/docs/blueprints/resilient-apps-multiple-machines/
https://fly.io/docs/blueprints/sticky-sessions/
https://fly.io/docs/blueprints/multi-region-fly-replay/
https://fly.io/docs/blueprints/remote-mcp-servers/
https://fly.io/docs/blueprints/review-apps-guide/
https://fly.io/docs/blueprints/per-user-dev-environments/
https://fly.io/docs/blueprints/using-base-images-for-faster-deployments/
Previewed all in local env
> Add 7 illustration links to guides-oct batch 1

- blueprints/autostart-internal-apps.html.md
- blueprints/connecting-to-user-machines.html.md
- blueprints/observability-for-user-apps.html.md
- blueprints/opensshd.html.md
- blueprints/supercronic.html.md
- blueprints/using-the-fly-docker-registry.html.md
- blueprints/volume-forking.html.md
Add image links to 7 guides
https://fly.io/docs/blueprints/using-the-fly-docker-registry/
https://fly.io/docs/blueprints/connecting-to-user-machines/
https://fly.io/docs/blueprints/opensshd/
https://fly.io/docs/blueprints/observability-for-user-apps/
https://fly.io/docs/blueprints/autostart-internal-apps/
https://fly.io/docs/blueprints/volume-forking/
https://fly.io/docs/blueprints/supercronic/
Previewed all in local env
> Add 7 illustration links to guides-oct batch 2
