superfly/docs

reference/postgres.html.md
Solves https://github.com/superfly/flyctl/issues/428
=> Remove unimplemented sections

getting-started/troubleshooting.html.md, reference/configuration.html.md, reference/services.html.md.erb
Adding some info in the troubleshooting section and also adding new ports
=> Adding some more sections to troubleshooting & adding new ports

getting-started/node.html.md
Use correct filename for the terminal command when testing out the express server
=> use correct filename for node command

hands-on/connecting-to-an-app.html.md
Going through guide and ran the above command which caused a 404. Updated to the correct path.
=> Fix URL issue causing 404

getting-started/multi-region-databases.html.md
Minor typo, but might trip up somebody who copy/pastes.
=> Fix mistake in Ruby example

getting-started/multi-region-databases.html.md
Adds documentation on how to restore a PG from a volume snapshot.
=> Postgres - Restore from Snapshot

reference/private-networking.html.md
See - https://community.fly.io/t/wireguard-client-setup-on-ubuntu/3942
=> Include openresolv for wg-quick to work in Ubuntu

flyctl/cmd/flyctl_machine.md, flyctl/cmd/flyctl_machine_status.md, flyctl/cmd/flyctl_postgres.md, flyctl/cmd/flyctl_postgres_connect.md
=> [flybot] Fly CLI docs update

reference/redis.html.md
Adds documentation for new options added in https://github.com/fly-apps/redis/pull/9 (not merged yet).
=> Update Redis documentation to reflect new configuration options

partials/_firecracker_nav.html.erb
This fixes a wrong url in the navigation bar for the "Run UDP Services" section.
=> Fix navigation url of "Run UDP Services"

getting-started/rails.html.md.erb
Adds some links to Redis and multi-process app documentation in the Rails guide.
=> Link to Redis and multi-process app docs

reference/postgres.html.md
Adding app flag to postgres attach example since the detach example has it
=> Add flag for app to attach example

app-guides/continuous-deployment-with-github-actions.html.md
=> Fix GitHub actions example typo

getting-started/crystal.html.md.erb
It seemed the other guides had "Bonus Points" sections, so I was copying that
However, this reads a ton nicer if we include a real heading here.
=> Improve heading for multi-region Crystal

reference/configuration.html.md
The original phrase `This may be set here in with '--strategy'.` sounds very strange.
=> improve `strategy` section initial paragraph

flyctl/cmd/flyctl_volumes_create.md, reference/volumes.html.md
fixes #138 per logbook https://fly.io/blog/logbook-2022-05-05/
=> update docs to reflect new default volume size

reference/configuration.html.md
* document PRIMARY_REGION usage in release commands
* reword the 'statics' docs to be more accurate
* Clean up other sections for clarity
=> Clarify copy in various fly.toml config sections

hands-on/sign-up.html.md
=> Remove extra period

reference/private-networking.html.md
=> Show how to run dig txt _apps.internal

getting-started/laravel.html.md.erb
1. More details on files to change if you need a different PHP version
2. Details on getting full stack traces in Fly's log output
=> Laravel docs update

reference/private-networking.html.md
=> Fix sentence in private networking docs

getting-started/golang.html.md.erb, getting-started/python.html.md.erb
I was reading the documentation and found what seems to be a couple of small typos. Hope this helps :)
=> Fix typo in Python & Go Getting Started docs

getting-started/nextjs.html.md.erb, partials/_firecracker_nav.html.erb, speedrun.html.md
Should be merged after flyctl releases it
=> Add nextjs docs

reference/configuration.html.md
Took Kurt's content from here: https://community.fly.io/t/preview-multi-process-apps-get-your-workers-here/2316
And turned it into docs.
=> Documenting the `processes` fly.toml section

speedrun.html.md
Small grammar fix on speedrun.html.md
=> grammar fix on speedrun.html.md

about/support.html.md
discussed in https://flyio.discourse.team/t/email-vs-community-support/683/9
=> add mention of status page to /about/support

app-guides/mysql-on-fly.html.md, partials/_firecracker_nav.html.erb
=> mysql on fly guide in docs

partials/_firecracker_nav.html.erb
Maybe this isn't where these links will go in the end, but people should be able to get to Phoenix Files and Laravel Bytes from docs somehow!
=> throw pf and lb links on docs nav

rails/advanced-guides/multi-region.html.md, rails/advanced-guides/multiple-applications.html.md, rails/index.html.md.erb, rails/the-basics.html.md, rails/the-basics/backup-and-restoring-data.html.md, rails/the-basics/configuration.html.md, rails/the-basics/run-tasks-and-consoles.html.md, rails/the-basics/sidekiq.html.md
This fixes various typos in the Rails documentation.
=> Fix typos in Rails documentation

reference/redis.html.md
- added `Connect to an Upstash Redis database` section
- some other minor updates
=> Updated Redis documentation

about/healthcare.html.md.erb, about/security.html.md, partials/_firecracker_nav.html.erb
Added healthcare page and link in main navbar, removed call to ask us about questionnaires and replaced it with links to SOC2 and healthcare pages + email for info.
=> Matt healthcare

README.md, reference/configuration.html.md, reference/load-balancing.html.md
Also, include a new page on load balancing 🎉
=> Add service.concurrency.type documentation for fly.toml

getting-started/launch-app.html.md.erb
=> Fix link to hands-on with fly page

laravel/the-basics/cron-and-queues.html.md
Pretty sure this "instance pf your codebase" is supposed to say "instance of your codebase"
=> Change simple typo "pf" to "of"

getting-started/troubleshooting.html.md
Line 145: "For example if you notice in your logs that the database if failing to connect..." should be: "For example if you notice in your logs that the database is failing to connect ..."
=> Typo, if instead of is

app-guides/udp-and-tcp.html.md.erb
Follows from: https://github.com/superfly/docs/commit/8f11c25b474ac2a46f851399fdb1330c89e61ba8
=> (udp app-guide): four gotchas

rails/getting-started/migrate-from-heroku.html.md
- `/bin/app/rails` -> `/app/bin/rails`
- `/bin/app/rake` -> `/app/bin/rake`
=> Heroku: Updates paths for app binaries

litefs/getting-started.html.md, litefs/index.html.md, partials/_litefs_nav.html.erb
I'll be adding a page on "How it works" and a "LiteFS Config" reference page separately.
=> Add 'Getting Started with LiteFS' page

reference/machines/create_app.html.md
reported [here](https://community.fly.io/t/fly-machine-virtual-machine-exited-abruptly-following-app-guide/7167/3)
=> remove trailing comma on last JSON field

rails/advanced-guides/sqlite3.html.md
=> Posgres -> Postgres

reference/security.html.md
Hi. I just fixed a few grammatical mistakes in `reference/security.html.md`.
=> Fix grammar in security.html.md

litefs/getting-started.html.md
=> fix: typos

hands-on/partials/_next.html.md
=> fix minor typo

getting-started/edgedb.html.md
=> Update and simplify EdgeDB guide

rails/getting-started/index.html.md
There is a confusing word repetition on line 42, I think only one "add" is needed. 
__A newly generated Rails application will display a flashy splash screen when run in development, but will do absolutely nothing in production until you code__
=> index.html.md

partials/_firecracker_nav.html.erb
Break out a "Database & Storage Guides" section so people can more clearly see that how they can persist and manage their data on Fly.
=> Reorganize docs sidebar

database-storage-guides.html.md, partials/_firecracker_nav.html.erb
Create landing page for DB and Storage guides
=> landing page for DB storage guides

postgres/index.html.md
Adding Neon managed Postgres free tier
=> Update index.html.md: Add Neon database Postgres

laravel/advanced-guides/global-sqlite-litefs.html.md.erb
Hopefully this small fix will format the `consul` yml content correctly
=> format the `consul` yml content correctly

app-guides/udp-and-tcp.html.md.erb
=> fix : minor typo

reference/private-networking.html.md, reference/redis.html.md
Fix: few Link breaks
Fixing few link breaks
=> Fix: few Link breaks

postgres/index.html.md, postgres/the-basics/configuration-tuning.html.md.erb, postgres/the-basics/enabling-timescale.htm.md.erb, postgres/the-basics/scaling.html.md.erb
Make scaling doc refer to the new configuration doc.
Some edits.
=> Take pg config out of scaling doc

postgres/connecting/connecting-external.html.md.erb, reference/architecture.html.md, reference/configuration.html.md, reference/services.html.md.erb
Also fix some longstanding broken internal links
=> Document pg_tls and usage

flyctl/integrating.html.md, getting-started/log-in-to-fly.html.md
=> Fix : minor typos

rails/the-basics/sidekiq.html.md
Please feel free to make/suggest edits if you feel the sentence is now _less_ explicit than before.
<hr />
Closes #296
=> Fix broken URL reference

partials/_flyctl_nav.html.erb
Remove dns, domains, suspend, resume. Add image.
=> Update flyctl ref menu items

app-guides/graphql-on-fly-with-hasura.html.md, app-guides/planetscale.html.md, flyctl/cmd/flyctl_image_update.md, laravel/the-basics/github-actions.html.md, rails/advanced-guides/machine.html.md, rails/advanced-guides/phusion-passenger.html.md, rails/advanced-guides/sqlite3.html.md, rails/getting-started/fly-rails.html.md, rails/getting-started/migrate-from-heroku.html.md, rails/the-basics/configuration.html.md, rails/the-basics/sidekiq.html.md, reference/postgres-on-nomad.html.md, reference/private-networking.html.md
I run a tool that searches for misspellings and typos and this is the result.
=> Spellcheck, fix typos

app-guides/continuous-deployment-with-github-actions.html.md
=> Minor typo fix

laravel/advanced-guides/global-sqlite-litefs.html.md.erb, reference/private-networking.html.md
These links are not resolvable in the hosted version of the docs
=> Change two links pointing to localhost:4567 to be relative instead

litefs/example.html.md.erb, litefs/getting-started.html.md.erb, litefs/position.html.md.erb, partials/_litefs_nav.html.erb
The previous guide was moved to the [LiteFS Example Application doc page](https://fly.io/docs/litefs/example/).
=> LiteFS Getting Started guide

laravel/advanced-guides/global-sqlite-litefs.html.md.erb, laravel/advanced-guides/multiple-applications.html.md
Need to first verify behavior regarding none-primary node write request redirection to primary node
=> revise laravel litefs guide to follow litefsv3 config

partials/_flyctl_nav.html.erb
Use flyctl_nav_link helper from https://github.com/superfly/landing/commit/456be93396a85f386cfa1ccaacc9bf36f3b91b47
=> Show flyctl commands in nav

django/index.html.md.erb, litefs/partials/_disclaimer.html.md, partials/_obsolete_doc.html.erb, rails/getting-started/index.html.md, rails/the-basics/backup-and-restoring-data.html.md, rails/the-basics/sidekiq.html.md, rails/the-basics/turbo-streams-and-action-cable.html.md
These were found by the [Algolia Crawler](https://crawler.algolia.com/admin/crawlers/2b697854-1962-4fd2-87b7-fae0dac6cb4d/monitoring/list?reason=http_not_found). 
Related https://github.com/superfly/landing/pull/379
=> Broken links in Docs

app-guides/edgedb.html.md, app-guides/mysql-on-fly.html.md, database-storage-guides.html.md
To make it clearer that Fly Postgres, LiteFS, and Upstash are special and everything else is generic
=> Differentiate Fly.io database projects from examples

app-guides/continuous-deployment-with-github-actions.html.md, app-guides/the-dreaded-port-filter.html.md.erb, index.html.md, languages-and-frameworks/dockerfile.html.md.erb, laravel/the-basics/databases.html.md.erb, machines/guides-examples/functions-with-machines.html.md.erb, rails/getting-started/index.html.md, reference/configuration.html.md
Earmark is more strict about markdown, these were the things it found and I fixed along the way. 
The largest changes are to the Laravel database page. Idk if @fideloper or @KTanAug21 want to take a peak but I check that the pages were nearly the same.
=> Various malformed markdown or html fixes.

app-guides/multiple-processes.html.md
Without pushing to `main` constantly, like some sort of monster
=> Updating multi-process docs page

elixir/advanced-guides/sqlite3.html.md, rails/advanced-guides/sqlite3.html.md
This guide goes quite a bit further than the Rails guide. Namely porting an existing application, porting an existing database, and sftp put'ing a existing database up into a volume.
I got @crumm's permission to attribute his gist as it was helpful!
=> Elixir SQLite

laravel/advanced-guides/github-actions.html.md, laravel/advanced-guides/global-sqlite-litefs.html.md.erb, laravel/partials/_volume_storage_script.html.md, laravel/partials/_volume_storage_steps.html.md.erb, laravel/partials/_volume_storage_warning.html.md, laravel/the-basics/databases.html.md.erb, laravel/the-basics/github-actions.html.md, laravel/the-basics/laravel-volume-storage.html.md.erb
Add section for mounting volume to the storage folder, which requires reinitialization after volume mount
=> Laravel volumized storage section

app-guides/continuous-deployment-with-github-actions.html.md
The sample file for GitHub actions contain some incorrect tabbing. This PR is to standardise all as 2 space for every tab.
=> Fix incorrect tab on yaml file.

app-guides/continuous-deployment-with-github-actions.html.md, django/getting-started/existing.html.md, elixir/advanced-guides/github-actions-elixir-ci-cd.html.md, elixir/getting-started/migrate-from-heroku.html.md.erb, elixir/index.html.md, flyctl/index.html.md, flyctl/installing.html.md, getting-started/index.html.md, getting-started/installing-flyctl.html.md, getting-started/launch-app.html.md.erb, getting-started/log-in-to-fly.html.md, getting-started/working-with-fly-apps.html.md, hands-on/index.html.md.erb, hands-on/install-flyctl.html.md.erb, hands-on/next.html.md.erb, hands-on/sign-in.html.md.erb, languages-and-frameworks/deno.html.md.erb, partials/_firecracker_nav.html.erb, partials/_flyctl_nav.html.erb, partials/flyctl/_auth_login.md.erb, postgres/connecting/connecting-with-flyctl.html.md.erb, rails/getting-started/fly-rails.html.md, rails/getting-started/index.html.md, rails/the-basics/backup-and-restoring-data.html.md, rails/the-basics/turbo-streams-and-action-cable.html.md, reference/index.html.md, reference/services.html.md.erb, signup-welcome.html.md
While trolling for Apps V2 changes
=> Tidying minor things I came across

reference/configuration.html.md
=> move time units note before parameter list

postgres/getting-started/what-you-should-know.html.md
Found a broken link when reading this doc. Found the full link to the intended reference and corrected it here.
=> Fix link to PlanetScale guide

machines/guides-examples/terraform-machines.html.md.erb
- update terraform to `0.0.20`
- remove dependency on wireguard running locally
- use new flags for tunnels
=> chore: update terraform-machines.html.md.erb

rails/getting-started/dockerfiles.html.md
=> Fix incorrect dockerfile command

litefs/example.html.md.erb
Remove the suggested app name so it always autogenerates it.
=> Fix LiteFS Example docs

machines/working-with-machines.html.md.erb
Should fix https://community.fly.io/t/is-there-a-starting-status-in-fly-machines/10929
=> Added `starting` status to docs

litefs/mount.html.md.erb
Fixes https://github.com/superfly/docs/issues/611
=> Fix link on LiteFS mount docs

rails/getting-started/index.html.md
There is a grammar issue in the sentence. Instead of "chose", it should be "choose" as it is in the present tense.
=> Fix grammer issue in index.html.md

reference/private-networking.html.md
ref: https://community.fly.io/t/cannot-connect-to-machines-on-internal-service-port/8330/5?u=griff
=> add section that explains how to listen on your private network

rails/the-basics/turbo-streams-and-action-cable.html.md
=> Add more code formatting to "Turbo Streams & Action Cable" guide

apps/info.html.md, django/getting-started/existing.html.md, elixir/getting-started/existing.html.md.erb, elixir/getting-started/migrate-from-heroku.html.md.erb, elixir/the-basics/iex-into-running-app.html.md, rails/getting-started/dockerfiles.html.md, rails/getting-started/existing.html.md, rails/getting-started/index.html.md, rails/getting-started/migrate-from-heroku.html.md, rails/the-basics/run-tasks-and-consoles.html.md
This is a very recent `flyctl` change (bringing it in line with how OpenSSH works). Provided I `grep`ped the docs carefully, these are all the example commands that should be updated.
=> Use `--pty` with `fly ssh console` when needed

about/pricing.html.md.erb
In first sentence - `about/pricing.html.md.erb`
I wasn't 100% sure on which word to use. "build" ? or "deploy" might be better. I went with "launch". Hope that's ok :)
=> Add missing word

partials/_flyctl_nav.html.erb
Added `flyctl status` to the nav sidebar. Also re-ordered 2 items.
=> Add flyctl status to sidebar

getting-started/troubleshooting.html.md
kudos to @jphenow who took the time to help a user here: https://community.fly.io/t/flyctl-deploy-not-running-failing-to-determine-start-command-started-just-today/12182/3
Mostly rewording his responses here :)
=> Adding section to troubleshooting for buildpacks-based builds

reference/volumes.html.md.erb
https://community.fly.io/t/largest-volume-size/12270
=> Explicitly mention the maximum size of volumes

reference/builders.html.md
=> fix grammar

elixir/the-basics/iex-into-running-app.html.md
Link at the bottom of the guide for running iEX to the next page was broken
=> Fix broken link

reference/extensions_api.html.md
This is for sending to potential partners while we work out the spec.
=> Add an unlinked Extensions API proposal

reference/extensions_api.html.md
This PR moves security-related content into a single section.
=> Fix up some content related to extensions API

reference/extensions_api.html.md
This reflects what is now deployed in production, for SSO.
=> Update Extensions API docs to reflect a simpler SSO flow

postgres/connecting/app-connection-examples.html.md.erb, postgres/connecting/connecting-external.html.md.erb
Formatting and updating to use a new fly command
=> PG docs updated

flyctl/cmd/flyctl_apps_create.md, flyctl/cmd/flyctl_deploy.md, flyctl/cmd/flyctl_launch.md
docs changes for https://github.com/superfly/flyctl/pull/2287
=> removed `--force-[nomad/machines]` and `--[nomad/machines]` flags

hands-on/check-app-status.html.md.erb, hands-on/launch-app.html.md.erb
This PR updates the Hand-on docs a little bit to show that 2 machines are created by default when you go through these steps.
=> Update Hands-on docs prompts and output

hands-on/install-flyctl.html.md.erb, rails/cookbooks/sources.html.md.erb, rails/getting-started/dockerfiles.html.md, rails/the-basics/configuration.html.md
=> style: Powershell -> PowerShell

app-guides/continuous-deployment-with-github-actions.html.md
The doc didn't have an explanation for step 8.
=> Add explanation for step 8 in Continuous deployment doc

django/getting-started/existing.html.md
Fixes https://github.com/superfly/docs/pull/499
=> Remove self-link

reference/private-networking.html.md
=> add <g>.process.<a>.internal to 6pn docs

partials/_flyctl_nav.html.erb
Add `console`, `settings`, and `tokens` commands to nav.
=> Update flyctl nav

apps/deploy.html.md.erb
Add the canary deploy strategy to the Deploy Apps page.
=> Add canary to deploy page

litefs/backup.html.md.erb
Fixing a minor typo in the new litefs backup doc!
=> Fix typo/duplicated text in litefs backup doc

apps/deploy.html.md.erb
=> Fix typo on deploy page

reference/extensions_api.html.md
Fixes a few things missed in #778
=> Fixes for Extensions API updates

machines/working-with-machines.html.md.erb
There was an [inquiry](https://community.fly.io/t/exposing-prometheus-metric-collection-for-machines/13019) on the community forum for this information.
=> Document `metrics` Machine configuration

reference/volumes.html.md.erb
Some minor edits for clarification of terms and functionality.
=> Minor edits to volumes reference

reference/app-availability.html.md.erb
This PR moves a note per @Johannes-Werbrouck's suggestion :)
=> Move note about Fly Proxy below the first mention of Fly Proxy

apps/volume-storage.html.md.erb, reference/volumes.html.md.erb
This PR clarifies the note about using two volumes with two Machines. Also, makes this a warning callout on both pages.
=> Some edits to volumes docs to make the bit about 2 volumes per Machine more clear

getting-started/working-with-fly-apps.html.md
This PR:
- fixes an issue with a hanging sentence and a command that wasn't updated (source: https://community.fly.io/t/working-with-fly-apps/13548)
- changes example domains to "example.com"
- hack fixes some issues with headings
=> Minor fixes to Working with Fly Apps page 

reference/index.html.md
This PR updates the reference index page: adds some new categories, updates all the descriptions for some slight consistency, adds links to pages that were missing.
=> Update the reference index page

app-guides/multiple-processes.html.md, apps/migrate-to-v2.html.md.erb, apps/processes.html.md.erb, apps/scale-count.html.md.erb, apps/volume-storage.html.md.erb, reference/volumes.html.md.erb
This PR attempts to clarify some text about regions and how to add and scale into them. There are also some minor edits done along the way, like fixing some title case in files I was looking at. :)
=> Updates here and there for some clarification about regions

apps/scale-count.html.md.erb
Be consistent and include the city for the region code in brackets after the code in each section.
Some discussuion: https://github.com/superfly/docs/pull/838
=> Consistent region mentions

reference/regions.html.md.erb
This PR updates the city name for the `bom` region.
=> update city name

apps/deploy.html.md.erb
This Pr fixes a typo and adjusts the wording in the deploy an app doc.
=> Fix typo and wording

litefs/index.html.md.erb, litefs/proxy.html.md.erb, litefs/speedrun.html.md.erb, reference/litefs/adding_litefs_to_your_dockerfile_deps.md, reference/litefs/create_litefs_cloud_cluster.md, reference/litefs/importing_your_database.md
I've addressed feedback from https://github.com/superfly/docs/pull/836.
=> Address litefs docs feedback

postgres/connecting/app-connection-examples.html.md.erb
…ing sequelize for node.js apps
=> Sequelize read-replica connection demo

languages-and-frameworks/dotnet.html.md.erb
This is a simple guide to run a .NET application, and it depends on the changes made in [this pull request](https://github.com/superfly/flyctl/pull/2533).
=> Guide: Run a .NET Application

machines/working-with-machines.html.md.erb
| Old | New |
|-------|--------|
| ![image](https://github.com/superfly/docs/assets/1713819/dd37a9a0-f17f-4fc9-8a00-325a966ce379) | ![image](https://github.com/superfly/docs/assets/1713819/55302199-e350-44da-906c-d0d95eec1536) |
=> Improve machines API navigation

machines/working-with-machines.html.md.erb, reference/configuration.html.md.erb
From https://community.fly.io/t/https-checks-now-support-true-tls-certificate-verification/14385
=> Document tls_server_name service keyword

machines/working-with-machines.html.md.erb, reference/configuration.html.md.erb
Related to https://github.com/superfly/docs/pull/908
Just some minor edits to new content for `files` feature
=> Edits to new files content

reference/configuration.html.md.erb
Add a note that you can't use bluegreen with volumes and that you need a health check.
=> Add info about bluegreen and volumes

apps/autostart-stop.html.markerb
By feedback I mean the linter we're testing.
=> Minor edits from feedback

about/extensions.html.markerb, reference/extensions_api.html.md
This brings docs in line with reality and exposes the API docs to interested parties.
=> Updates to the extensions API docs

about/extensions.html.markerb, partials/_firecracker_nav.html.erb, reference/extensions_api.html.md
This PR includes updates for the extension provisioning API docs including:
* Mentioning support and billing
* Fixing the provisioning response shape to match reality
* Adding detail about Flycast provisioning IP addresses for services
* Discussing emailing customers
=> More updates to the extensions API docs

litefs/disaster-recovery.html.markerb, litefs/getting-started-docker.html.markerb, litefs/proxy.html.markerb, litefs/speedrun.html.markerb
Fixes https://github.com/superfly/docs/issues/958
=> Fix LiteFS docs links

reference/secrets.html.markerb
=> Mention `fly secrets deploy` command

reference/app-availability.html.markerb, reference/apps.html.markerb, reference/architecture.html.md, reference/build-secrets.html.md, reference/fly-launch.html.md, reference/volumes.html.markerb
Random edits made while testing Vale linter
=> Some fixes from running and testing vale

app-guides/run-a-global-image-service.html.markerb, apps/scale-machine.html.markerb, elixir/the-basics/troubleshooting.html.md, languages-and-frameworks/crystal.html.markerb, litefs/cloud-backups.html.markerb, litefs/config.html.markerb, machines/guides-examples/machines-app-using-flyctl.html.markerb, postgres/getting-started/migrate-from-heroku.html.md, postgres/managing/scale-to-zero.html.markerb, rails/cookbooks/index.html.md, reference/extensions_api.html.md
found by Vale :)
(plus a couple typos)
=> Remove repeated words

reference/sentry.html.md
Updated docs to fix 2 spelling/grammar issues
=> Fixed typos in sentry.html.md

.github/workflows/vale-docs-linter.yml
tested in forked branch and seems to be working now
=> Fix linter action to lint changed and new files

laravel/advanced-guides/global-sqlite-litefs.html.markerb
Changed a single sentence to remedy a grammatical error (replaced "none-file" with "non-file").
n/a
n/a
=> Grammatical fix: replaced "none-file" with "non-file"

litefs/config.html.markerb
Added config updates for `proxy.primary-redirect-timeout` and `lease.databases`
- https://github.com/superfly/litefs/pull/407
- https://github.com/superfly/litefs/pull/408
n/a
=> Update config docs for LiteFS v0.5.7

about/pricing.html.markerb
Adds pricing details about LiteFS Cloud to the pricing page.
- https://community.fly.io/t/litefs-cloud-is-generally-available/15677
n/a
=> Add LiteFS Cloud pricing

litefs/events.html.markerb
Minor copy pasta fix.
- https://community.fly.io/t/is-this-doc-example-correct-for-litefs-events/15766
n/a
=> Fix 'primaryChange' message type in docs

elixir/the-basics/clustering.html.md
=> Replacing libcluster with dns_cluster

styles/Fly/Spelling.yml, styles/words2ignore.txt
Add the words "args" and "deprioritize" the the spelling ignore file.
n/a
n/a
=> Add words to ignore file

reference/configuration.html.markerb
In Fly launch config page > services section > http checks, add information about the tls_server_name parameter.
=> In Fly launch config page > services section > http checks, add information about the tls_server_name parameter.

elixir/the-basics/iex-into-running-app.html.md
=> Fix link to next page in the guide

styles/Vocab/Fly-terms/accept.txt
Add some new terms to Vale. 
n/a
n/a
=> Update vale accept list with more terms

reference/configuration.html.markerb
Document the `max_unavailable` field in the `[deploy]` section of `fly.toml`.
https://github.com/superfly/flyctl/pull/2905
=> Document `fly.toml#deploy.max_unavailable`

getting-started/troubleshooting.html.md
=> docs: fix typo

styles/Vocab/Fly-terms/accept.txt
Add some words we use to the list of acceptable words for the Vale linter.
n/a
n/a
=> Vale: add some more acceptable words

machines/index.html.md
=> a whack at a new /docs/machines

about/pricing.html.markerb
- add a sentence about what an org is
- remove unclear language
- add info about additional orgs paid Hobby plan
- link to volumes docs
n/a
n/a
=> Update wording on pricing page

machines/index.html.md
=> Delete superfluous $ prompts

reference/configuration.html.markerb, reference/volumes.html.markerb
* https://github.com/superfly/flyctl/pull/3023
* https://github.com/superfly/flyctl/pull/3031
* https://github.com/superfly/flyctl/pull/3038
n/a if none
=> Document `mounts.initial_size`

gpus/gpu-quickstart.html.markerb
Update GPU quickstart guide to reflect simplifications on launching gpu apps
n/a if none
n/a if none
=> Update GPU quickstart guide

going-to-production/monitoring/exporting-logs.html.md
=> Add 'Configuring Vector' section to the Fly Log Shipper docs

partials/_machines_nav.html.erb
minor adjustment to Machines nav
n/a
n/a
=> adjust machines nav a bit because i am not chill

machines/working-with-machines.html.markerb
- add update header section
- copy note from create into update section
- update heading title and anchor links for config section
#1175 
n/a
=> API docs: minor adds/fixes after last update

about/pricing.html.markerb, app-guides/mysql-on-fly.html.markerb, apps/info.html.md, apps/processes.html.markerb, apps/restart.html.markerb, machines/guides-examples/machines-app-using-flyctl.html.markerb, partials/_firecracker_nav.html.erb, postgres/getting-started.html.markerb, postgres/index.html.md, postgres/managing/cluster-resources.html.markerb, postgres/managing/forking.html.markerb, postgres/managing/horizontal-scaling.html.markerb, postgres/managing/monitoring.html.markerb, postgres/managing/scaling.html.markerb, postgres/managing/upgrades.html.markerb
- remove Postgres docs V2 banner
- make adjustment or remove sections that reference how to do things on V1 apps
- #1187 
n/a
n/a
=> Remove more v1 content

reference/apps.html.markerb
make a few edits and add links
n/a
n/a
=> Minor edits to apps ref page

about/billing.html.markerb, about/pricing.html.markerb
Add info about how you're charged for all existing volumes, regardless of if they're attached or not. Add slightly different content to pricing and billing pages.
https://community.fly.io/t/question-about-pricing-model/16562/3
n/a
=> Add info about how volumes are billed to pricing page

app-guides/continuous-deployment-with-github-actions.html.md, app-guides/mysql-on-fly.html.markerb, apps/deploy.html.markerb, postgres/managing/backup-and-restore.html.markerb
Update docs for `fly launch` UI:
- Continuous deployment doc
- MySQL guide
- fly deploy doc
- postgres backups
n/a
n/a
=> Update some docs for fly launch ui

django/getting-started/existing.html.md
This reflects recent changes in `flyctl`.
=> Updated getting started docs for existing django apps.

apps/launch.html.markerb
- update the Fly Launch page a bit to adjust for the launch ui
- some other wording changes for hopefully clarity, less words
n/a
n/a
=> Edits to launch page for launch ui

js/frameworks/nextjs.html.markerb
Fixed some typos, added extra clarity arounding using the dockerfile node package.
https://fly.io/docs/js/frameworks/nextjs/
n/a if none
=> Cleaned up NextJS documentation

apps/processes.html.markerb, apps/scale-machine.html.markerb
The flyctl `--process-group` and `--group` options were recently consolidated into `--process-group` and `-g`. Yay!
https://github.com/superfly/flyctl/pull/3062
n/a
=> Update process group option

reference/private-networking.html.md
- the table header row needed some capitalization
- other minor edits while there for Machine, Fly.io, etc.
n/a
n/a
=> Private networking: table header row and minor edits

app-guides/fauna.html.md
- `fly regions set` doesn't work, so updated the example to use `fly scale count`.
#900 
@zeekhoo please comment if there are any issues
=> Update Fauna doc with scale info

getting-started/troubleshooting.html.md, machines/working-with-machines.html.markerb, reference/architecture.html.md, reference/deploy-tokens.html.md, reference/machines.html.markerb, reference/private-networking.html.md
fix capitalization of WireGuard
n/a
n/a
=> capitalize WireGuard

machines/guides-examples/machine-restart-policy.html.markerb
=> Add missing word to restart policy doc

partials/_firecracker_nav.html.erb, reference/supabase.html.md
To accompany the beta launch
https://supabase.com/blog/postgres-on-fly-by-supabase
=> Add Supabase to sidebar

apps/autostart-stop.html.markerb, index.html.md
Changed Typescript --> TypeScript case typo
n/a
n/a
=> fix Typescript --> TypeScript case typo

apps/launch.html.markerb
=> Fix typo on Fly Launch page

js/the-basics/database.html.md
=> docs: fixed typo accomplisedh -->  accomplished

postgres/advanced-guides/high-availability-and-global-replication.html.markerb
- update the HA Postgres doc for flex
- partial fix for #648 
n/a
=> Update HA Postgres doc for flex

styles/Vocab/Fly-terms/accept.txt
add words to the accepted vocabulary list
n/a
n/a
=> Vale: update accept list

app-guides/continuous-deployment-with-github-actions.html.md
-add optional concurrency key
- update bit about copying the token to include the prefix `FlyV1` and space
- clarify which instance of `master` in the yaml  file to update if needed
- #1159
- https://community.fly.io/t/help-with-continuous-deployment-through-github/17572
n/a
=> Updates to GitHub Actions doc

app-guides/custom-domains-with-fly.html.md
This PR should be merged after https://github.com/superfly/web/pull/2643
=> Wildcard certs don't require dedicated IPs

js/the-basics/listening-ports.html.md
fix a single spelling mistake
replaced "an" with "and" in "any number between 1024 an 65535."
thats it.
=> Minor spelling mistake

django/advanced-guides.html.md, django/advanced-guides/staging-environments-with-github-actions.html.md, django/index.html.markerb
Documentation page based on my latest [article](https://fly.io/django-beats/staging-environments-on-the-fly-with-github-actions/).
=> Doc'd creating staging envs for Django projects with GitHub actions.

laravel/database-guides/laravel-mysql.html.markerb, networking/dynamic-request-routing.html.md, networking/index.html.markerb
Re: the missing text, tbh I suspect my cat.
n/a
n/a
=> Fix links + missing text

machines/guides-examples/functions-with-machines.html.markerb, machines/index.html.md, partials/_firecracker_nav.html.erb
update links, remove a link to a thing that doesn't exist right now
n/a
n/a
=> Update some Machines links

reference/regions.html.markerb
=> regions.html.markerb: fix typo

postgres/getting-started/what-you-should-know.html.md
This is actually 5 days as noted elsewhere in the documentation, this one just slipped by the cracks.
=> Update mention of 7-day snapshot retention.

about/billing.html.markerb, about/pricing.html.markerb
talk about how much stopped machines cost
[n/a if none](https://community.fly.io/t/we-are-going-to-start-collecting-charges-for-stopped-machines-rootfs-starting-april-25th/17825)
n/a if none
=> add rootfs price descriptions

speedrun.html.markerb
Adding more graphics to the Speedrun page.
Fixes https://github.com/superfly/ui-ex/issues/1574
n/a if none
=> Add more graphics to speedrun

partials/_firecracker_nav.html.erb
=> Move machines up in nav

apps/scale-count.html.markerb, index.html.md, laravel/database-guides/laravel-mysql.html.markerb, machines/api-apps-resource.html.markerb, machines/api-machines-resource.html.markerb, machines/guides-examples/machine-restart-policy.html.markerb, machines/guides-examples/machine-sizing.html.markerb, reference/extensions_api.html.md
=> Fix links to new Machines API sections

gpus/index.html.md
Remove GPU waitlist blurb
n/a if none
n/a if none
=> remove gpu header part 2

partials/_sign_in.html.erb
Add a bit of test about what the command for WSL users does. 
Fixes #1036 
n/a
n/a
=> Update wsl user note in sign in partial

reference/configuration.html.markerb
Document `gpus` fly.toml field  
* https://github.com/superfly/flyctl/pull/3199
n/a if none
=> Document "gpus = N" for multi GPU support

elixir/getting-started/existing.html.markerb, elixir/getting-started/index.html.markerb, elixir/getting-started/migrate-from-heroku.html.markerb, languages-and-frameworks/partials/_launch_with_postgres.html.erb
- update elixir launch partial for the launch ui and other launch output updates
- a few minor changes to the files that use the partial
https://community.fly.io/t/app-launch-stuck-in-pending/17735
n/a
https://aa-docs.fly.dev/docs/elixir/getting-started/
=> Update elixir launch content

machines/guides-examples/machine-sizing.html.markerb
See title.
n/a if none
n/a if none
=> Fix link to fly machines section on pricing page

app-guides/supercronic.html.md
=> Update supercronic version

js/frameworks/astro.html.markerb
=> Added correct layout for astro

machines/api-volumes-resource.html.markerb
- add the snapshot on-demand creation endpoint and examples (beta)
- other minor edits and fixes (change order, add missing endpoint)
n/a
n/a
=> API docs: updates to volumes resource

gpus/getting-started-gpus.html.md
Added links to docs for Fly Proxy autostop and terminating idle Machines. 
Community member asked for more clarity on how fast GPU Machines will shut down when idle; this is better than nothing
https://community.fly.io/t/get-help-with-fly-gpus/18218/4?u=catflydotio
=> GPU quickstart: link to docs for autostop and exit when idle 

reference/volumes.html.markerb
Removed wording "for improved performance at deployment and runtime."
[HS](https://secure.helpscout.net/conversation/2516377015/81657?folderId=6453875)
[Discourse](https://flyio.discourse.team/t/non-encrypted-volumes/4989/2)
=> Removed certain wording for volume encryption

reference/index.html.md
Maybe temporary update to reference landing page
=> Update ref landing page

machines/api-apps-resource.html.markerb, reference/machines/_machines_create_req.erb, reference/machines/_machines_lease_create_req.erb, reference/machines/_machines_lease_get_req.erb, reference/machines/_machines_lease_release_req.erb
Caught some more characters that need escaping and some tabs that don't display well
=> escape some more things

partials/_firecracker_nav.html.erb
Move Machines section above the fold - incremental step to increase visibility
=> Move machines up in main nav

machines/guides-examples/functions-with-machines.html.markerb
Quick grammar fix on the Machines docs. 
https://fly.io/docs/machines/guides-examples/functions-with-machines/
=> Update functions-with-machines.html.markerb to fix grammar issues

machines/api/machines-resource.html.markerb
=> API docs: Add redirect

machines/api/apps-resource.html.markerb, machines/api/volumes-resource.html.markerb
=> API docs: redirects again

index.html.md
=> Fix links on main page

machines/api/index.html.md
=> API docs: add image to Machines API page

machines/runtime-environment.html.md
Fix the redirect (it's currently redirecting from itself!).
Reported on the community forum: https://community.fly.io/t/cant-find-info-about-runtime-environment-variables/18493
=> Fix `machines/runtime-environment/` redirect

machines/api/apps-resource.html.markerb, machines/api/machines-resource.html.markerb, machines/api/volumes-resource.html.markerb, reference/machines/_machines_cordon_req.erb, reference/machines/_machines_create_req.erb, reference/machines/_machines_create_serv_req.erb, reference/machines/_machines_delete_req.erb, reference/machines/_machines_get_req.erb, reference/machines/_machines_lease_create_req.erb, reference/machines/_machines_lease_get_req.erb, reference/machines/_machines_lease_release_req.erb, reference/machines/_machines_list_req.erb, reference/machines/_machines_metadata_delete_req.erb, reference/machines/_machines_metadata_get_req.erb, reference/machines/_machines_metadata_update_req.erb, reference/machines/_machines_start_req.erb, reference/machines/_machines_stop_req.erb, reference/machines/_machines_update_req.erb, reference/machines/_machines_wait_req.erb
remove them all! except for the ones in the endpoints tables.
=> API docs: remove escaped underscores

flyctl/index.html.md, flyctl/integrating.html.md, partials/_firecracker_nav.html.erb, partials/_flyctl_nav.html.erb, partials/_machines_nav.html.erb
- make flyctl nav start open
- make machines nav start open
- some minor adjustments to flyctl content
- make flyctl nav not refer to Reference section anymore (was a bit confusing)
=> Adjust nav settings for amazing new collapsible nav

litefs/primary.html.markerb, partials/_litefs_nav.html.erb
Also add a redirect for a broken link.
=> New nav for litefs docs too!

postgres/connecting/app-connection-examples.html.markerb
Added Django to the app connection examples and corrected headers.
=>  Added Python and Django to app connection examples for PostgreSQL. 

about/open-source.html.markerb, apps/scale-count.html.markerb, apps/trouble-host-unavailable.html.markerb, machines/api/machines-resource.html.markerb, postgres/advanced-guides/high-availability-and-global-replication.html.markerb, postgres/getting-started/enabling-timescale.html.markerb, rails/cookbooks/sources.html.markerb, rails/getting-started/dockerfiles.html.md, rails/getting-started/existing.html.md, reference/build-secrets.html.md
fix some broken links and file things
=> wip: fixing links for fun

kubernetes/clusters.html.markerb, kubernetes/configuring-services.html.markerb, kubernetes/fks-quickstart.html.markerb, kubernetes/index.html.markerb, kubernetes/services.html.markerb, partials/_firecracker_nav.html.erb
Adds a section our support for Kubernetes Services
=> add documentation on services

database-storage-guides.html.md
=> Add Supabase and Tigris to database/storage landing page

postgres/getting-started/what-you-should-know.html.md
The link currently points to a section that doesn't exist.
=> fix broken postgres configuration link

postgres/connecting/connecting-internal.html.markerb, postgres/connecting/connecting-with-flyctl.html.markerb, postgres/getting-started/create-pg-cluster.html.markerb, postgres/getting-started/what-you-should-know.html.md, postgres/index.html.md, postgres/managing/deleting.html.markerb, postgres/managing/horizontal-scaling.html.markerb, postgres/managing/upgrades.html.markerb, postgres/managing/users-and-roles.html.markerb
- add link to Supabase on Fly.io
- remove empty right navs
- fix bullet in nav issue
=> Postgres docs: add link to Supabase on Fly.io, rm empty right navs

reference/redis.html.md
Upstash is replacing empty response discounts with fixed price plans, coming soon.
=> Remove mention of Sidekiq and empty response discounts for Upstash Redis

about/billing.html.markerb, about/pricing.html.markerb
Use Started vs Running in heading.
=> Pricing: started Machines

hands-on/launch-app.html.markerb
Remove an old redirect from the deploy page to the launch page that was breaking new things.
=> Hands-on: rm redirect

kubernetes/services.html.markerb
Add documentation on configuring Fly.io concurrency limits when using K8s services
=> document configuring service concurrency

machines/flyctl/fly-machine-run.html.md
Couple of typos and one other extra word removed.
=> Remove typos/extra word

index.html.md
=> Update docs main page for new Metrics and Logs section

machines/index.html.md
=> Machines docs: minor edits to landing page

reference/concurrency.html.markerb
- add info about new connection for each http request
- add links to where to configure concurrency
- fix headings
#1446
=> Concurrency: add info about new connection for each http request

app-guides/review-apps-guide.html.md
This adds a guide to setting up review apps on Fly.io. Article is available at `/docs/app-guides/review-apps-guide`
=> Added review apps guide

app-guides/review-apps-guide.html.md, partials/_firecracker_nav.html.erb
=> Add Review Apps doc to nav

kubernetes/clusters.html.markerb, kubernetes/connect-clusters.html.markerb, kubernetes/fks-quickstart.html.markerb, kubernetes/index.html.markerb, kubernetes/services.html.markerb, kubernetes/using-volumes.html.markerb
Add related topic links for new docs and update a few other links.
=> FKS: update related topic links

networking/private-networking.html.md
* list autostart and autostop first among reasons to use Flycast
* clarify what Flycast is
* didn't fix all typos etc in file
=> Flycast docs -- make autostart/stop use case prominent

about/pricing.html.markerb, kubernetes/clusters.html.markerb, kubernetes/connect-clusters.html.markerb, kubernetes/fks-quickstart.html.markerb, kubernetes/index.html.markerb, kubernetes/services.html.markerb, kubernetes/using-gpus.html.markerb, kubernetes/using-volumes.html.markerb
Changes wording for how we describe FKS on our pricing page and changes the in beta message to reflect that its in open beta.
=> Fks wording

apps/volume-manage.html.markerb, reference/volumes.html.markerb
Add that you can fork a volume into another region now.
=> Add info about cross-region volume forks

kubernetes/services.html.markerb
Documents how to use TLS options in an FKS service
=> document tls options

blueprints/index.html.erb, blueprints/review-apps-guide.html.md, blueprints/run-a-global-image-service.html.markerb, partials/_firecracker_nav.html.erb
=> Let's try blueprints

blueprints/supercronic.html.md
=> Fix redirect

kubernetes/fks-quickstart.html.markerb, kubernetes/using-gpus.html.markerb
Use an actually relevant example
=> use a gpu app in gpu example

blueprints/opensshd.html.md, kubernetes/services.html.markerb, reference/error-codes.html.md, reference/extensions_api.html.md
Fixed some typos in docs.
Some backgrounds on how theses typos are fixed, I've wrote a (Chinese) blog about this: https://nova.moe/fast-typo-fix/ (English version: https://nova.moe/fast-typo-fix-en/) 😇
=> Fixed some typos in docs

networking/custom-domain.html.markerb
Added some information about the top level domains we currently support. This should help customers who use custom domains.
=> Add supported tlds

rails/getting-started/existing.html.md
Trivial grammar and spelling corrections.
Some spelling and grammatical corrections.
=> Copyediting for existing.html.md

reference/deploy-tokens.html.md
Style consistency. CLI program is flyctl; commands are `fly`.
=> Convert some commands from flyctl to fly

languages-and-frameworks/axum.html.markerb, rust/frameworks/axum.html.markerb
- Adds axum framework quickstart
=> [draft] add rust axum docs

partials/_firecracker_nav.html.erb
=> Remove volumes from db & storage nav

volumes/volume-manage.html.markerb
a really long bit of inline code was extending beyond the text column; changed it to a codeblock
=> format fix in volumes doc

machines/api/apps-resource.html.markerb, machines/api/index.html.md, machines/api/machines-resource.html.markerb, machines/api/tokens-resource.html.markerb, machines/api/volumes-resource.html.markerb, machines/api/working-with-machines-api.html.markerb, partials/_machines_nav.html.erb
-  add tokens resource and links
- add a status code table
=> API docs: tokens and status codes

styles/Fly/WordList.yml
=> Update WordList.yml: 'leverage'

reference/regions.html.markerb
removed checkmark on fly.io/docs/reference/regions/
ref hs91654
=> bom does not have wg gateways

blueprints/deno-kv-litefs.html.md
- Add blueprint for using Deno KV with LiteFS
https://jesse-deno-litefs.fly.dev/
=> Deno KV with LiteFS

blueprints/deno-kv-litefs.html.md
- fixup deno KV blueprint typo/wording
=> more consistent wording on the deno KV blueprint

getting-started/essentials.html.md
=> Fix incorrect anchor

app-guides/multiple-processes.html.md, apps/processes.html.markerb
- replace some old links with new doc links
- clarify that one doc is about multi process apps in general and the other is about configuring process groups
- other minor updates
=> Update multi-process apps doc

machines/api/apps-resource.html.markerb, machines/api/machines-resource.html.markerb, machines/api/working-with-machines-api.html.markerb
- add `enable_subdomains` to Apps resource
- update response codes
=> API docs: updates

blueprints/resilient-apps-multiple-machines.html.md
Trying some changes for better flow and scanning
https://aa-docs-2.fly.dev/docs/blueprints/resilient-apps-multiple-machines/
=> Multi-machine blueprint: add sub-headings and move benefits

styles/config/vocabularies/fly-terms/accept.txt
Add nameserver and Ollama to word list
=> Add words to vale accept list

getting-started/essentials.html.md
- fix typo
- wording updates for clarity/concision
=> Essentials: typo and wording changes

blueprints/connect-private-network-wireguard/index.html.md
make the youtube embed link for this blueprint use "enhanced privacy mode"
=> nocookie youtube embed link

about/support.html.md
https://community.fly.io/t/email-support-response-metrics/20004/8
=> Link to Support Metrics Dashboard

partials/_firecracker_nav.html.erb, reference/machine-migration.html.markerb
An overview of the process for migrating Machines between hosts from a draft by @kzys 
https://aa-docs.fly.dev/docs/reference/machine-migration/
https://community.fly.io/t/psa-machine-migration-has-started-again/20265
=> Add Machine migration reference doc

about/billing.html.markerb
Update the billing page with new plan info.
=> Update billing page for PAYG

styles/config/vocabularies/fly-terms/accept.txt
=> Add Valkey to linter's accept.txt

apps/trouble-host-unavailable.html.markerb, blueprints/autostart-internal-apps.html.md, blueprints/multi-region-fly-replay.html.md, blueprints/resilient-apps-multiple-machines.html.md, networking/dynamic-request-routing.html.md, reference/app-availability.html.markerb
links to docs from blueprints and to blueprints from docs
=> Link blueprints in docs

kubernetes/fks-quickstart.html.markerb
=> fix typo in fks quickstart

reference/arcjet.html.md
Temporarily remove numbering because it doesn't get rendered correctly.
cc @jsierles
=> Remove numbering

partials/_firecracker_nav.html.erb
=> remove shared responsibility from nav

flyctl/install.html.markerb, getting-started/launch-demo.html.markerb, getting-started/sign-up-sign-in.html.markerb, partials/docs/_flyctl_install.html.erb
=> Adjust hands-on redirects

js/frameworks/astro.html.markerb, js/frameworks/deno.html.markerb, js/frameworks/nextjs.html.markerb, js/frameworks/nuxtjs.html.markerb, js/frameworks/redwood.html.markerb, js/frameworks/remix.html.markerb, js/frameworks/svelte.html.markerb, languages-and-frameworks/dockerfile.html.markerb, languages-and-frameworks/dotnet.html.markerb, languages-and-frameworks/golang.html.markerb, languages-and-frameworks/ruby.html.markerb, languages-and-frameworks/static.html.markerb, python/frameworks/fastapi.html.markerb, python/frameworks/flask.html.markerb, python/frameworks/streamlit.html.markerb, rust/frameworks/actix-web.html.markerb, rust/frameworks/axum.html.markerb, rust/frameworks/dioxus-liveview.html.markerb, rust/frameworks/poem.html.markerb, rust/frameworks/rocket.html.markerb, rust/frameworks/warp.html.markerb
Add all frameworks to sitemap :upside_down_face:
=> remove sitemap: false flag

networking/tls.html.md, partials/_firecracker_nav.html.erb, security/index.html.markerb, security/tls-termination.html.markerb
Add a page that describes very briefly how Fly Proxy terminates TLS.
=> Add tls termination

index.html.md, security/index.html.markerb
Update main page content to divide into sections that are a bit more "card-like".
https://aa-docs-3.fly.dev/docs/
=> Main page re-org

index.html.md
=> Main page: minor word changes

database-storage-guides.html.md
- streamline the bit about volumes
- create a section for object storage for Tigris
- create a section for managed dbs
- move Fly.io dbs below these
- edited/cut down extra text
- defined sections similar to main page
=> Update Databases & Storage page

blueprints/private-applications-flycast.html.md
Copies https://youtu.be/PR0rzkwKwFA into the docs
https://community.fly.io/t/run-private-applications-with-flycast/20387/1
Like #1575, but using youtube-nocookie.com for the embed so that people don't get cookies set on their machines.
=> blueprints: add Flycast video/blueprint

getting-started/launch-demo.html.markerb, partials/_sign_up.html.erb
- minor edits to sign up partial
- update fly launch output and wording since users won't _have_ to change the app name anymore. Add explanation about app names.
- edit the bit about fly.toml
=> Launch demo: updates

machines/api/working-with-machines-api.html.markerb
https://community.fly.io/t/understanding-fly-io-api-rate-hard-limits/20636
=> Publish Machine API rate limits

laravel/the-basics/laravel-tigris-file-storage.html.markerb, laravel/the-basics/laravel-volume-storage.html.markerb
Added a Tigris Laravel doc page detailing steps on integrating Tigris with a Laravel (fly) app
NA 
There's already an[ existing PR](https://github.com/superfly/docs/pull/1622) for this, but I created this because there's an issue with its checks. This branch is created from an updated nmain branch, so hopefully I don't get the same check error
=> Finalize tigris laravel initial docs page

reference/tigris.html.md
WIP: waiting on one more guide
=> Tigris docs: add links to framework guides

laravel/the-basics/laravel-tigris-file-storage.html.markerb, styles/config/vocabularies/fly-terms/accept.txt
Fix spelling in recent Laravel Tigris docs page
=> fix spelling

apps/trouble-host-unavailable.html.markerb, getting-started/troubleshooting.html.md, metrics-and-logs/error-codes.html.md, metrics-and-logs/index.html.markerb, metrics-and-logs/logs.html.markerb, partials/_firecracker_nav.html.erb
- fix some typos
- move content under metrics and logs
- rename to "Fly.io errors and troubleshooting"
- add links to this doc from other troubleshooting docs
- fixes #1581
=> Error codes: fix typos and move to log section

blueprints/private-applications-flycast.html.md
=> Minor fixes to adjust for doc vs video script

blueprints/private-applications-flycast.html.md
=> more adjustments to blueprint

networking/udp-and-tcp.html.markerb
- simplified
- moved the configuration/gotchas to the top
- stopped calling them gotchas and removed multiple "we're working on it"s
- reworded the headings and moved them up a level
- seemingly random edits
- left in the bit about eBPF magic despite my instinct to edit that too (might go back to it though)
=> Update the UDP doc a little

machines/api/machines-resource.html.markerb
https://flyio.slack.com/archives/C05CDMQ3ELC/p1720440341889279
=> Fix API docs for volume mounts on machine creation

apps/autostart-stop.html.markerb, networking/dynamic-request-routing.html.md, partials/_firecracker_nav.html.erb, reference/architecture.html.md, reference/fine-tune-apps.html.markerb, reference/fly-proxy.html.markerb, reference/load-balancing.html.md
We don't have a doc about Fly Proxy and all it does. ~~This is the beginning of that doc.~~ This is that doc.
=> A doc about Fly Proxy

partials/_firecracker_nav.html.erb, reference/load-balancing.html.md
- fix proxy nav entry
- add bit about connection pool to load balancing doc
=> Minor fixes for proxy doc

launch/scale-machine.html.markerb, launch/volume-storage.html.markerb, reference/load-balancing.html.md
=> Add redirects and fix typo

blueprints/autostart-internal-apps.html.md, blueprints/going-to-production-with-healthcare-apps.html.md, blueprints/opensshd.html.md, blueprints/resilient-apps-multiple-machines.html.md
Corrected Typos in Blueprints document
n/a
n/a
n/a
=> Corrected Typos in Blueprints

js/frameworks/meteor.html.markerb
=> Meteor updates

apps/move-app-org.html.markerb, partials/_apps_nav.html.erb
Move an app to a new org as suggested and started by @Lucais11
=> Add doc to move app to a new org

about/pricing.html.markerb
Add documentation for the new pricing model for bandwidth.
=> Add documentation for new bandwidth pricing

about/pricing.html.markerb, apps/going-to-production.html.markerb, blueprints/deno-kv-litefs.html.markerb, index.html.md, litefs/backup.html.markerb, litefs/cloud-backups.html.markerb, litefs/cloud-restore.html.markerb, litefs/disaster-recovery.html.markerb, litefs/getting-started-docker.html.markerb, litefs/getting-started-fly.html.markerb, litefs/index.html.markerb, litefs/speedrun.html.markerb, partials/docs/_litefs_sunset.html.erb
- add banner to relevant LiteFS Cloud and pricing docs
- remove LiteFS Cloud step from speedrun
- etc.
https://community.fly.io/t/sunsetting-litefs-cloud/20829
=> LiteFS Cloud - add sunsetting banner

machines/api/machines-resource.html.markerb, reference/configuration.html.markerb
Documentation for serving files with Tigris, an alternative method for serving statics
=> tigris documentation

js/frameworks/meteor.html.markerb
=> Meteor sticky sessions with `fly-replay`

monitoring/metrics.html.md, monitoring/search-logs.html.markerb
add redirects missed when creating monitoring section!
=> Add missing redirects

reference/enveloop.html.md
* Updated syntax on `dashboard` command.
* Tightened up some wording.
* Reordered a couple of sections to improve flow.
=> Command updates

blueprints/sticky-sessions.html.md
=> add nav for sticky session blueprint

about/pricing.html.markerb
Explain how Fly Postgres pricing works
fixes: #1700
=> Pricing: add a section on Postgres

launch/autoscale-by-metric.html.markerb
- update the descriptions for the `FAS_CREATED_MACHINE_COUNT` and `FAS_STARTED_MACHINE_COUNT` values
fixes #1644
=> Autoscaler doc: update config descriptions

python/partials/_poetry_new.erb, python/the-basics/initial-setup.html.md, python/the-basics/multi-stage-builds.html.md
Added some minor clarifications about the dockerfile and poetry usage
=> Python clarifications

languages-and-frameworks/golang.html.markerb
=> fix anchor link and adjust wording

machines/api/machines-resource.html.markerb
=> Add `suspend` Machines API endpoint to list

launch/scale-count.html.markerb
=> Add missing redirect

blueprints/review-apps-guide.html.md
=> Fix typos in review apps guide

litefs/backup.html.markerb, litefs/cloud-backups.html.markerb, litefs/cloud-restore.html.markerb
This adds setup instructions for using Litestream with LiteFS.
https://community.fly.io/t/sunsetting-litefs-cloud/20829
=> Add docs for using Litestream with LiteFS

litefs/backup.html.markerb
=> Add Litestream AWS secrets

about/pricing.html.markerb
=> Clarify that Machines reservations apply only to CPU/RAM charges.

about/pricing.html.markerb
This PR adds docs about opting into the new bandwidth pricing.
=> Add docs about opting in to granular bandwidth pricing

blueprints/autostart-internal-apps.html.md, blueprints/connect-private-network-wireguard/index.html.md, networking/flycast.html.markerb, networking/index.html.markerb, networking/private-networking.html.md, partials/_firecracker_nav.html.erb, reference/fly-proxy.html.markerb
=> Flycast in the spotlight, or at least its own page

networking/flycast.html.markerb
=> remove redirect

python/frameworks/fastapi.html.markerb
=> fix fastapi dep to use the correct group

launch/autoscale-by-metric.html.markerb
=> Update autoscale-by-metric - fix typo in `secrets set` cli command

networking/flycast.html.markerb
- add `fly launch --flycast` and `fly deploy --flycast`
- add headings
- add `--network` option
- rearrange and shorten things
https://aa-docs-2.fly.dev/docs/networking/flycast/
=> Update Flycast doc with more info + headings

blueprints/autostart-internal-apps.html.md, blueprints/private-applications-flycast.html.md, launch/processes.html.markerb, networking/app-services.html.md, networking/index.html.markerb, reference/configuration.html.markerb, reference/extensions_api.html.md, reference/kafka.html.md, reference/redis.html.md, reference/vector.html.md
- update autostop/autostart blueprint with `--flycast` option.
- update links
=> Add and fix flycast links

networking/private-networking.html.md
Edits to private networking, mostly to add links to Flycast.
=> Update private networking doc - Flycast links

partials/_accordion.html.erb, partials/_accordion_nav.html.erb, partials/_firecracker_nav.html.erb, partials/_simple_list.html.erb
Adds another layer of nesting. 
Old:
New:
=> Nested log links

about/billing.html.markerb
Unified Billing (Aggregated Billing) documentation.
=> unified billing docs

about/billing.html.markerb
=> Revert "unified billing docs"

about/billing.html.markerb
=> Unified billing

index.html.md, partials/_accordion_nav.html.erb, partials/_breadcrumbs.html.erb
=> Unbork nav and add breadcrumbs

partials/_breadcrumbs.html.erb
=> Fixes legal breadcrumbs

about/pricing.html.markerb
We just dropped the price on L40S GPUs by half; reflect that on the pricing page
https://fly.io/blog/cutting-prices-for-l40s-gpus-in-half/
=> change l40s price to 1.25

launch/autostop-autostart.html.markerb, reference/fly-proxy-autostop-autostart.html.markerb
=> Minor edits to autostop/autostart docs

blueprints/resilient-apps-multiple-machines.html.md, blueprints/staging-prod-isolation.html.md, machines/guides-examples/functions-with-machines.html.markerb, networking/custom-private-networks.html.markerb, networking/flycast.html.markerb, networking/private-networking.html.md, partials/_firecracker_nav.html.erb
- add a new doc about custom private networks and how to use them
- minor edits and links in other docs
=> Add custom network docs

blueprints/autoscale-machines.html.md, blueprints/cell-based.html.md, blueprints/connect-private-network-wireguard/index.html.md, blueprints/multi-region-fly-replay.html.md, blueprints/sticky-sessions.html.md
=> minor updates to blueprints

happy-path/aim.html.markerb, happy-path/application.html.markerb, happy-path/fire.html.markerb, happy-path/index.html.markerb, happy-path/postgresql.html.markerb, happy-path/ready.html.markerb, happy-path/recap.html.markerb, happy-path/redis.html.markerb, happy-path/tigris.html.markerb, happy-path/whisper.html.markerb, partials/_demo_nav.html.erb
- add a new nav
- edit content and some on-page re-org
=> Demo updates: edits + re-org some content + nav

partials/_breadcrumbs.html.erb
=> Adding lvl metadata to make this suck less

apps/going-to-production.html.markerb
Added:
- Flycast
- mention the cost savings of autoscaling and add cost to the availability section title
- scaling regions
- made support section part of "checklist"
- changed fine-tune section title to "App performance"
- changed order of sections
https://aa-docs.fly.dev/docs/apps/going-to-production/
=> Going to Production: add more items

networking/dynamic-request-routing.html.md, networking/index.html.markerb, tigris/index.html.markerb
Add some of devrel's videos into the docs. More to come.
=> Add a few embedded videos

happy-path/index.html.markerb
Feedback and minor edits/fixes.
=> Deep dive feedback

about/pricing.html.markerb
=> Remove `pricing` from the heading

machines/cpu-performance.html.md, styles/config/vocabularies/fly-terms/accept.txt
=> quick update about perf vCPUs getting 100% quota

deep-dive/index.html.markerb
=> Update index.html.markerb: fix typo

index.html.md
=> Fix header image for mobile sceens

index.html.md
Update the homepage design and content
=> Homepage update

gpus/getting-started-gpus.html.md, gpus/gpu-quickstart.html.markerb, gpus/index.html.md
=> Update GPU regions availability

mpg/overview.html.md
=> Revert "fix: update image paths in Managed Postgres overview"

mpg/overview.html.md
updated image path for main doc image.
=> fix: update image path in Managed Postgres overview

mpg/overview.html.md
=> fix: update image path to use /static/images/

reference/load-balancing.html.md
Clarified that soft_limit only affects in-region load balancing and does not trigger cross-region routing. Updated some examples so that they align with actual Fly Proxy behavior and eliminate misleading implications.
=> WIP(clarify cross-region, hard_limit, and soft_limit)

blueprints/setting-concurrency-limits.html.md
Adding blueprint post for how to set and tune hard and soft limits
Tested/previewed locally
=> add concurrency limits blueprint

gpus/getting-started-gpus.html.md, gpus/gpu-quickstart.html.markerb, gpus/index.html.md
Added in ams as a region for our GPUs
=> Added ams region for GPUs

security/arcjet.html.md
Added a link to https://arcjet.com/pricing
=> Added Arcjet pricing link

apps/concurrency.html.markerb
add link to concurrency limits blueprint to concurrency settings doc
=> add link to concurrency limits blueprint

machines/guides-examples/machine-placement.html.md, partials/_machines_nav.html.erb
New doc based on Sol Arch guide & Fresh Produce post
https://community.fly.io/t/regional-capacity-in-machines-api-and-flyctl/24843
=> add new doc: machine placement and regional capacity

machines/guides-examples/machine-placement.html.md
- Point to correct navigation (machines)
- Update article publication date
=> fix frontmatter to machines side nav

blueprints/observability-for-user-apps.html.md
fixed broken relative links in observability blueprint
checked links locally
=> fix links in observability blueprint

flyctl/cmd/fly_machine.md
=> Fix typo in fly_machine.md.

blueprints/seamless-deployments.html.md
New doc for zero-downtime deployments and health checks. 
Based on a topic from the Solutions Architecture guide
Checked in local preview env
=> add seamless deployment guide

mpg/create-and-connect.md, mpg/extensions.md, mpg/import.md
Adds expanded Managed Postgres (MPG) docs.
=> Add MPG create+connect, extensions, and import docs

mpg/create-and-connect.html.md, mpg/extensions.html.md, mpg/import.html.md, mpg/index.html.md
- enable right-side TOC 
- add publication date to frontmatter
=> add toc and date to MPG docs

about/pricing.html.markerb
Update static egress IPs section to clearly state pricing
=> Update static egress IP section

apps/move-app-org.html.markerb, blueprints/autoscale-machines.html.md, blueprints/bridge-deployments-wireguard.html.md, blueprints/going-to-production-with-healthcare-apps.html.md, getting-started/launch-demo.html.markerb
Add links to 4 new illustrations
- https://fly.io/docs/blueprints/bridge-deployments-wireguard/
- https://fly.io/docs/blueprints/autoscale-machines/
- https://fly.io/docs/blueprints/going-to-production-with-healthcare-apps/
- https://fly.io/docs/getting-started/launch-demo/
Add link to 1 existing illustration
https://fly.io/docs/apps/move-app-org/
Change docs links to relative
Tested in local environment
=> add 5 illustration links and change links to relative

blueprints/autoscale-machines.html.md, rails/advanced-guides/sqlite3.html.md, rust/frameworks/dioxus-liveview.html.markerb
Closes these issues
https://github.com/superfly/docs/issues/2152
https://github.com/superfly/docs/issues/2149
https://github.com/superfly/docs/issues/1887
Previewed locally
=> Minor docs fixes from repo issues

networking/understanding-cloudflare.html.md
Clarified A record interference in CDN proxy setup with Cloudflare. Also changed the file extension to `.html.md`
=> clarify A record interference in CDN proxy setup with Cloudflare

mpg/index.html.md
- Add MPG regions that are coming soon (we can move them to the main list when they're actually available)
- Added US state to be consistent with our main regions list doc
Previewed locally
=> add mpg regions coming soon

machines/api/apps-resource.html.markerb, networking/custom-private-networks.html.markerb
Updated docs for [list-apps](https://fly.io/docs/machines/api/apps-resource/#list-apps-in-an-organization) endpoint.
=> docs(machines-api): add volume_count field to apps_list endpoint

about/support.html.md
- Add a section heading for MPG support and move up
- Add MPG support info to Support portal section
- Reorganize headings to group free vs. paid support options
previewed in local env
=> update mpg support info and reorganize sections

kubernetes/fks-features.html.markerb, mpg/create-and-connect.html.md, postgres/connecting/connecting-external.html.markerb, postgres/index.html.md, rails/getting-started/migrate-from-heroku.html.md
- add links to 5 new illustrations - aug 2025 batch 1
Previewed locally
- Create Cluster: https://fly.io/docs/mpg/create-and-connect/#creating-a-managed-postgres-cluster-from-flyctl
- Migrate your app: https://fly.io/docs/rails/getting-started/migrate-from-heroku/
- Kubernetes Features: https://fly.io/docs/kubernetes/fks-features/
- Postgres: https://fly.io/docs/postgres/
- Factory: https://fly.io/docs/postgres/connecting/connecting-external/
PR to add images: 
https://github.com/superfly/landing/pull/1020
=> add links to new illustrations aug 2024 batch 1

mpg/index.html.md
Adds a pricing chart to the Postgres overview page.
=> Update Postgres Overview to include pricing chart

reference/aws-to-fly-guide.html.md
- update database info to MPG
- add related reading section
- add a few relevant links
- minor copy edits
Previewed in local env
=> updates to aws to fly migration doc

deep-dive/application.html.markerb, deep-dive/postgresql.html.markerb, deep-dive/redis.html.markerb, hiring/index.html.md, upstash/redis.html.md
https://fly.io/docs/deep-dive/redis/
https://fly.io/docs/upstash/redis/
https://fly.io/docs/deep-dive/postgresql/
https://fly.io/docs/deep-dive/application/
https://fly.io/docs/hiring/
Previewed in local env.
=> Add illustration links aug 2025 batch 2

blueprints/rollback-guide.html.md
- copy fix for --max-unavailable command
=> Rollback guide fix: change from percentage to float for --max unavailable

blueprints/n-tier-architecture.html.md
- new guide for blueprints section covering n-tier architecture on Fly
- expanded from Sol Arch sessions/guide
=> Add new guide: Getting started with n-tier architecture

reference/suspend-resume.html.md
This isn't obvious, and should be mentioned.
=> show how to suspend your own machine

blueprints/volume-forking.html.md
- new guide to using Fly Volume forking
- expanded from topic in Solution Architecture guide
- internal draft received tech and content reviews
=> Add new guide: Using Fly Volume forks for faster startups

database-storage-guides.html.md, partials/_firecracker_nav.html.erb
- update databases and storage section to show current recommended solutions including MPG
- update navigation
=> Update databases and storage section overview

about/support.html.md, monitoring/index.html.markerb
- remove warning on monitoring page
- update About > Support table to removed "Limited Support" column and move Monitoring to "Supported" column
=> Clarify monitoring support status

monitoring/metrics.html.md
=> docs on instance exit metrics.

postgres/getting-started/what-you-should-know.html.md, postgres/index.html.md
Warning for entire section (via `framework_docs` layout was added in PR https://github.com/superfly/landing/pull/1044
- update recommended database solutions
- add (unmanaged) to page title
- remove old warning that is replaced by the section-wide one
=> Update UPG pages with MPG recommendation

blueprints/shared-nothing.html.markerb
- update image link and formatting to be consistent with other Guides pages
- edit intro
- fix product names
=> update image link for shared nothing arch guide
